### ISSUE TITLE
Correct Implementation of load permissions after login (authentication)

### ISSUE THREAD

**Issue by stefanwuthrich** [AlexKhymenko/ngx-permissions#10]
I have an implementation question.
I have app, where auth.service is loading permissions (roles) after authentication.
After I call loadPermissions in every component or module, i need to check auth.
But I have feeling, that this is not correct way. You load in your example app (hardcoded) permission in app.component and I am wondering, where is correct place to load permissions, after authentication, without needed to load them every time (in every component etc) i need to check perm.
Can you please give me an advise ?

**Comment by AlexKhymenko** [comment]
Just load them in your authentication service. This.authenticate(url).switchmap(loadpermission).do((perm) => this.permissionServise.loadPermissions(perm)
Sorry from mobile phone

**Comment by AlexKhymenko** [comment]
It totally depends on your business logic. You can load them in canActivate guard. Father authentication. Or even before application starts. Checkout wiki page. I'm sorry I'm on vacation :-)

**Comment by stefanwuthrich** [comment]
tks for help and enjoy vacation :-)

**Comment by AlexKhymenko** [comment]
Thank You. Have a good day.

**Comment by meherett** [comment]
example please

**Comment by AlexKhymenko** [comment]
https://github.com/AlexKhymenko/ngx-permissions/wiki/common-use-cases

**Comment by meherett** [comment]
Thanks Thanks Thanks
