### ISSUE TITLE
Usage in component

### ISSUE THREAD

**Issue by faradoxuz** [AlexKhymenko/ngx-permissions#100]
How can check the permission in .ts files in for loop?

**Comment by AlexKhymenko** [comment]
Just use service. this.permissionsService.hasPermission

**Comment by faradoxuz** [comment]
it returns promise and could not return value from promise

**Comment by AlexKhymenko** [comment]
mmm sorry i didn't get the notification You can Use like this

`this.permissionsService.hasPermission.then((value) => {}) `

value will be the type of boolean.

**Comment by AlexKhymenko** [comment]
its better that you show pseudo code that you want to write

**Comment by AlexKhymenko** [comment]
If there any problems let me know/
