### ISSUE TITLE
Redirect to Previous URL after Login with Auth Guard

### ISSUE THREAD

**Issue by andreadompe** [AlexKhymenko/ngx-permissions#101]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
</code></pre>

## Current behavior

How can i redirect to previous URL after Login?

## Environment

<pre><code>
Angular version: X.Y.Z
ngx-permissions version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by andreadompe** [comment]
When i select url (ex. https://mysite.com/orders)
if i'm not logged the system bring me to the login page,
after the login how can i move the user to the previous page (/orders) ?

**Comment by AlexKhymenko** [comment]
Hi @andreadompe this is actually not library functionality. The the solution is to save the url that user is trying to navigate to some service. And when user loges in just check if there is such url store is yes navigate to that url.
