### ISSUE TITLE
ngxPermissionOnly Issue

### ISSUE THREAD

**Issue by xyrintech** [AlexKhymenko/ngx-permissions#102]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

`*ngxPermissionsOnly` does not work if used on any HTML native element - div, a etc.
But if the same thing used in mg-template with `[ngxPermissionsOnly]="['ADMIN']" `then this works

Below one works
```
<ng-template [ngxPermissionsOnly]="['Stripboard']">
                    <li><a class="nav-item nav-link" routerLinkActive="active" routerLinkActiveOptions="{ exact: true }"
                            [routerLink]="['/stripboard']">Stripboard</a></li>
                </ng-template>
```

Below one is not working
```
<li *ngxPermissionsOnly="['ADMIN', 'GUEST']"><a class="nav-item nav-link" routerLinkActive="active" routerLinkActiveOptions="{ exact: true }"
                    [routerLink]="['/stripboard']">Stripboard</a></li>
```
## Environment

<pre><code>
Angular version: 7.0.3
ngx-permissions version: ^6.0.5

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX

**Comment by sutkovoy** [comment]
It works in example https://plnkr.co/edit/GSAKjeFDfpLjMvC2y11u?p=preview. Are you sure everything is correct in your code?

**Comment by AlexKhymenko** [comment]
Hi @xyrintech we are using this in production and everything works. Can you check your code.
