### ISSUE TITLE
ngxPermissionsExcept not working correctly with multiple roles

### ISSUE THREAD

**Issue by soyiatgit** [AlexKhymenko/ngx-permissions#103]
I have recently started using ngxPermissions (https://www.npmjs.com/package/ngx-permissions#multiple-permissions) for handling accesses in my angular app. However, I face difficulties when I have multiple roles for the same user. Example:

`<ng-template [ngxPermissionsExcept]="['SPECIAL_ROLE']">
    // special text here
</ng-template>`

I want that the above code should be visible to everyone who has a role other than SPECIAL_ROLE. Now I have a user who has following roles:

['SPECIAL_ROLE', 'NORMAL_ROLE', 'SUPER_ROLE']
Since this user has roles other than SPECIAL_ROLE too, I expect the above code to be displayed to such a user. However, it turns out that using my code above this user do not see this code at all.

Cam you please suggest how to achieve the above use case.

Edit: I have tried few things and realize that may be ngxPermissions uses just the first role from the array to arrive at the decision. Is it so ? Thanks

**Comment by AlexKhymenko** [comment]
Good Day @soyiatgit . This is how library works. If You wrote 

 `<ng-template [ngxPermissionsExcept]="['SPECIAL_ROLE']">` - it means if user have this role it will not show the view in this page.

**Comment by soyiatgit** [comment]
Hi, Really appreciate your time to answer.

Can you please explain, how can I achieve my use case. In other words, how can we check using the library that a view should not be shown only when it has explicitly a single role. If it contains any other role also, then the view be shown.

**Comment by AlexKhymenko** [comment]
Hi @soyiatgit it actually depends how you  are using roles. Unfortunately right now what you want to achieve with roles is not possible. But with permissions its possible. Just turn all roles if you can to permissions  and then use custom function

` this.permissionsService.addPermission('shouldBeOnlySpecialRole', (permissionName, permissionsObject) => {
        return Object.keys(permissionsObject).length === 1 && !!permissionsObject[permissionName] ;
    });`

`<ng-template [ngxPermissionsExcept]="['shouldBeOnlySpecialRole']">`

**Comment by soyiatgit** [comment]
Yes, this is exactly what I am doing at the moment. 

Thanks for your confirmation that this is not possible right now. Hope the library will support the same in future.

**Comment by AlexKhymenko** [comment]
@soyiatgit Yes this will add more functionality to the library i will add It

**Comment by AlexKhymenko** [comment]
Added in 7.0.2

**Comment by soyiatgit** [comment]
Can you please link to some documentation how this works now in 7.0.2. Do we still simply have to put the user in ngPermissionExcept and the library automatically handles it or have you added any new directive for such cases.
