### ISSUE TITLE
preloading permissons

### ISSUE THREAD

**Issue by JesustheLord** [AlexKhymenko/ngx-permissions#104]
Hi as per user doc i am using the below snippet to load permissions before app start. but its not working. throws error like undefined method **loadPermissions**. Please Help me
{
provide: APP_INITIALIZER,
 useFactory: (ds: AuthService, ps: NgxPermissionsService) => function () { return ps.loadPermissions(JSON.parse(localStorage.getItem('roles')['permissions'])) },
deps: [NgxPermissionsService],
 multi: true
},

**Comment by AlexKhymenko** [comment]
what exactly doesnt' work?

**Comment by JesustheLord** [comment]
On browser refresh pages went blank Since Permissions used in Guard to protect the routes. I referred the document and found the above **APP_INITIALIZER**
method to over come it. 
I used the above shared snippet and facing the below error. 
![error](https://user-images.githubusercontent.com/3406506/58483385-d373fd80-817d-11e9-95a0-d312bcc014c1.JPG)

**Comment by AlexKhymenko** [comment]
Did you add forRoot?
