### ISSUE TITLE
Upgrading to Angular 8

### ISSUE THREAD

**Issue by hack2024** [AlexKhymenko/ngx-permissions#105]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

I intent to upgrade my version of angular from version 7 to version 8 and i get this "Incompatible peer dependencies found"
Package "ngx-permissions" has an incompatible peer dependency to "zone.js" (requires "^0.8.4", would install "0.9.1").

## Expected behavior

Upgrading to Angular 8 without problems of dependencies

## Minimal reproduction of the problem with instructions

ng update @angular/cli @angular/core

## Environment

<pre><code>
Angular version: 7.1.1
ngx-permissions version: ^6.0.5

**Comment by AlexKhymenko** [comment]
Fixed in version 6.0.6
