### ISSUE TITLE
angular 8 - enableIvy": true

### ISSUE THREAD

**Issue by lubkoKuzenko** [AlexKhymenko/ngx-permissions#106]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

ng serve
**ERROR in ENOENT: no such file or directory, open 'd:/site/node_modules/ngx-permissions/ngx-permissions.js'**
## Expected behavior

no error
## Minimal reproduction of the problem with instructions

need to enable Ivy renderer in tsconfig.app.json

"angularCompilerOptions": {
    "enableIvy": true
  },

## Environment

<pre><code>
Angular version: 8.0.0
ngx-permissions version: 6.0.6

>node -v
v12.3.1

>npm -v
6.9.0

**Comment by AlexKhymenko** [comment]
@lubkoKuzenko Thank You. I will look into it. But ivy is not really ready and there are a lot of bugs :-)

**Comment by dbusacca** [comment]
It's not a Ivy bug, ivy is exposing an error in the generated package.json

The package.json contains

> "main": "ngx-permissions.umd.js",
> "module": "ngx-permissions.js",
> "jsnext:main": "ngx-permissions.js",

But the .js entry files on the archive are

> ngx-permissions.umd.js
> index.js

So the ngx-permissions.js referenced on the package.json doesn't exists

If you change it to 

> "module": "index.js",
> "jsnext:main": "index.js",

it works.

Maybe @AlexKhymenko you can convert the project in an @angular/cli library.

**Comment by StickNitro** [comment]
Same problem for me with Angular v8, please see issue raised in [angular/angular#30781](https://github.com/angular/angular/issues/30781)

**Comment by AlexKhymenko** [comment]
regarding this issue it will be fixed on 14

**Comment by AlexKhymenko** [comment]
A actually migrated to the cli but i can't  make it work with ivy cause im having this issue https://github.com/angular/angular/issues/29363 a little bit later will try again

**Comment by AlexKhymenko** [comment]
https://github.com/angular/angular-cli/issues/14594

**Comment by AlexKhymenko** [comment]
@lubkoKuzenko I have fixed it in version 7 can You please verify. If some problems let me know. Just to clarify with version 7 of ngx-permissions minimal version of angular is 8

**Comment by jbjhjm** [comment]
7.0.2 runs fine with ng 8 for me. With Ivy enabled, the initial error `ERROR in ENOENT: no such file or directory, open 'd:/site/node_modules/ngx-permissions/ngx-permissions.js'`seems to be gone. Compiled successfully, but now there are lots of other things to solve. But that's a different story. This bugs seems to be solved for me.
