### ISSUE TITLE
And - OR condition

### ISSUE THREAD

**Issue by xyrintech** [AlexKhymenko/ngx-permissions#107]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Currently [ngxPermissionsOnly]="['Admin','Guest']" checks whether both are available or not.

## Expected behavior
[ngxPermissionsOnly]="['Admin','Guest']"  
If any of Admin or Guest is available then its allowed.

**Comment by AlexKhymenko** [comment]
Mmmmm actually they are checking if any available :-) can you Please check code

**Comment by xyrintech** [comment]
My point is there should be a way to specify where we need to have OR or AND case for permissions.

**Comment by AlexKhymenko** [comment]
@xyrintech  ok but in case if i need something like this 

`ADMIN && GUEST || SPECIAL` how to do like this one

**Comment by xyrintech** [comment]
Yes, exactly.

**Comment by AlexKhymenko** [comment]
Actually in such case You create Your own role and write rules in the function, There you have acess to all permissions  :-)

**Comment by BrkCoder** [comment]
Hey @AlexKhymenko is this feature is on the last version of ngx-permissions 7.0.3 because I have tried to type in the following manner "ADMIN && GUEST" and the library act like this is a single permission, can you supply a better example for this case ?

**Comment by AlexKhymenko** [comment]
Hi @BrkCoder . To do This You have 2 options create role and supply this two permissions. In Roles it's checking with and operator. Or add new permission 

`
this.permissionsService.addPermission('SUPER_USER', (permissionName, permissionsObject) => {
        return !!permissionsObject['ADMIN'] && !!permissionsObject['GUEST'] ;
    }); `
