### ISSUE TITLE
Checking permissions, not role

### ISSUE THREAD

**Issue by bbalkonsky** [AlexKhymenko/ngx-permissions#113]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x ] Feature request
[ x ] Documentation issue or request
</code></pre>

I have a view:
`<ng-template *ngxPermissionsOnly="['EDITOR']">
<some_code>
</ng-template>`

and component:
`this.permissionsService.addPermission(['permissionA', 'permissionB']);
    this.rolesService.addRole('EDITOR', ['permissionA', 'permissionB']);`

How can i check specific permission in view (like 'permissionA'), not a whole role?
like:
`<ng-template *ngxPermissionsOnly="['permissionA']">`

**Comment by AlexKhymenko** [comment]
actually You can write 

`<ng-template *ngxPermissionsOnly="['permissionA']">`


So what are You doing is right :-)

**Comment by bbalkonsky** [comment]
after addPermission and addRole i use `this.permissionsService.loadPermissions(['EDITOR']);`
in view
`<ng-template *ngxPermissionsOnly="['permissionA']">`
doesn't work, but `[ngxPermissionsOnly]="['EDITOR']"` works fine.
What am I doing wrong?

**Comment by bbalkonsky** [comment]
my bad, just confused in usage notations
