### ISSUE TITLE
Can't bind to 'ngxPermissionsOnly' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by indowebdeveloper** [AlexKhymenko/ngx-permissions#114]
Hello

I'm using Angular 6 and still new in it..
Then i'm trying to use this package but still have no luck with it

my problem is i'm try to use ngxPermissionsOnly inside the component of shared module

So my scenario is like this

1. I load the user permissions array from backend on app.component.ts and using loadPermissions to load all of the permissions
2. in my app.module i import the ngxPermissionsModule.forRoot() and my SharedModule
![image](https://user-images.githubusercontent.com/25521335/62451042-b2d8ad00-b797-11e9-9558-1c93088be103.png)
3. In my Shared Module, i exports the NgxPermissionsModule and the component i'm talking about which is "LeftSidebarComponent"
![image](https://user-images.githubusercontent.com/25521335/62451141-de5b9780-b797-11e9-8977-b888074d5433.png)
4. Then in my LeftSidebarComponent .html i'm trying to use like this
```
<div *ngxPermissionsOnly="['TEST']">
    dummy text
  </div> 
```
But have this error
![image](https://user-images.githubusercontent.com/25521335/62451278-1f53ac00-b798-11e9-8dfd-d847ffaa7ef3.png)

Am i do something wrong here ? any clue would be appreciated.. :D 
Thankyou

**Comment by indowebdeveloper** [comment]
Nvm, i forgot to import the permissionModule on the shared module.. :D

**Comment by AlexKhymenko** [comment]
@indowebdeveloper  Try to import ngxPermissionsModule. Cause You only export it
