### ISSUE TITLE
Issue with unit tests - NullInjectorError: No provider for NgxPermissionsStore

### ISSUE THREAD

**Issue by lubkoKuzenko** [AlexKhymenko/ngx-permissions#117]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

```
NullInjectorError: StaticInjectorError(DynamicTestModule)[NgxPermissionsService -> NgxPermissionsStore]: 
  StaticInjectorError(Platform: core)[NgxPermissionsService -> NgxPermissionsStore]: 
    NullInjectorError: No provider for NgxPermissionsStore!
```

## Expected behavior

No errors

## Minimal reproduction of the problem with instructions

Lazy loaded module module.ts
<code>NgxPermissionsModule.forChild()</code>

Inside component template i'm just using directive 
<code>*ngxPermissionsOnly</code>

In .spec file

```
beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [..., NgxPermissionsModule.forChild()],
      providers: [],
      declarations: [...,
        NgxPermissionsAllowStubDirective
      ]
    });
  }));
```

## Environment

<pre><code>
Angular version: X.Y.Z
ngx-permissions version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Hi please use specifically created  components https://github.com/AlexKhymenko/ngx-permissions/wiki/Testing

**Comment by lubkoKuzenko** [comment]
thanks, after some time it's working. Issue can be closed.
