### ISSUE TITLE
I have quick question i have loaded my roles via the RolesService how do i use or check against them say in the html template. For permissions it's simple by using the Permission directive. but for roles what do you use?

### ISSUE THREAD

**Issue by joelmuskwe** [AlexKhymenko/ngx-permissions#12]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z
ngx-permissions version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Good day. ngxPermissionsOnly, ngxPermissionsExcept directive is both for roles and permissions.

**Comment by joelmuskwe** [comment]
Thank you for a quick response and an awesome library.
