### ISSUE TITLE
Checking has all permissions

### ISSUE THREAD

**Issue by dimonx3** [AlexKhymenko/ngx-permissions#123]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

I have a user with multiple permissions `permission-A` and `permission-B`. I check them with `only` property:
```javascript
{
    path: 'admin/my-route',
    component: MyComponent,
    canActivate: [NgxPermissionsGuard],
    data: {
        permissions: {
            only: ['permission-A', 'permission-B']
        }
    }
}
```
It works like **has any permission**. Check that the user has **one** of the permissions.
`permission-A` **OR** `permission-B`.
## Expected behavior

It should works like **has all permissions**. Should check that the user has **all** permissions.
`permission-A` **AND** `permission-B`.
**How to configure `only|except` properties to check all permissions?**
## Environment

<pre><code>
Angular version: 7.2.13
ngx-permissions version: 7.0.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
@dimonx3 For this case You can use role. cause role uses and operator. Or You can create Your own role and pass there function.
