### ISSUE TITLE
Is it possible to use 'and' with ngxPermissionsOnly?

### ISSUE THREAD

**Issue by CarmenTalnariu** [AlexKhymenko/ngx-permissions#125]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[x ] Documentation issue or request
</code></pre>

## Current behavior

I would like to specify multiple permissions that the user needs to have in order to complete an action. The issue is that he needs to have all permissions not just one of them, so the logic needs to be "and" not "or". 

## Expected behavior

Something like this example:
```
<div *ngxPermissionsOnly="['Read' && 'Write']">
    <div>You can see this text </div>
</div>
```

I have researched but haven't found any solution.

**Comment by AlexKhymenko** [comment]
@CarmenTalnariu In this case You have to create role. In roles its using && operator. Sorry for late response. Or Also You can create customer function.

**Comment by abalad** [comment]
In a project I also work with RULES, and I really needed to perform a validation where the USER needs to have all the permissions to access certain functionality.
