### ISSUE TITLE
StaticInjectorError(AppModule)[NgIf -> TemplateRef]

### ISSUE THREAD

**Issue by SrHuevo** [AlexKhymenko/ngx-permissions#128]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
</code></pre>

## Current behavior
My application throw "StaticInjectorError(AppModule)[NgIf -> TemplateRef]" and I belive that import all NgxPermissionsModule necessary.

This is my app.module.ts:
<pre><code>
@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    NgxPermissionsModule.forRoot()
  ],
  bootstrap: [AppComponent],
})
export class AppModule {
}
</code></pre>

This is my shared.module.ts
<pre><code>
import {NgModule} from '@angular/core'
import {SidenavComponent} from './components/sidenav/sidenav.component'
import {NgxPermissionsModule} from 'ngx-permissions'

@NgModule({
  imports: [
    NgxPermissionsModule.forChild(),
  ],
  declarations: [
    SidenavComponent,
  ],
  exports: [
    NgxPermissionsModule,
    SidenavComponent,
  ],
})
export class SharedModule {
}
</code></pre>

This is my sidenav.component.html, where error throw
```
    <li *ngFor="let page of pageList">
        <a [ngxPermissionsOnly]="page.permission" >
            {{page.name}}
        </a>
    </li>
```

I too use 'NgxPermissionsService' in user.service.ts
<pre><code>
import {NgxPermissionsService} from 'ngx-permissions'

@Injectable({
  providedIn: 'root',
})
export class UserService {

  constructor(private permissionsService: NgxPermissionsService) {
  }

  saveLoggedUser(userData: IUser) {
    this.loggedUser = userData
    this.permissionsService.loadPermissions(userData.permissions)
  }
}
</code></pre>

## Environment

<pre><code>
Angular version: 7.0.0
ngx-permissions version: 7.0.3
</code></pre>

**Comment by AlexKhymenko** [comment]
This is connected to ngIf. Just import common module. Not connected to the library.
