### ISSUE TITLE
NgxPermissionsModule.forRoot returns a ModuleWithProviders type without a generic type argument.

### ISSUE THREAD

**Issue by faradoxuz** [AlexKhymenko/ngx-permissions#131]
NgxPermissionsModule.forRoot returns a ModuleWithProviders type without a generic type argument. Please add a generic type argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, please contact the library authors.

**Comment by monstrege** [comment]
This should have been done for Angular 9, now Angular 10 complains for real.
@AlexKhymenko : Are you still updating this library?

The documentation for this change is here: https://angular.io/guide/migration-module-with-providers.

**Comment by AlexKhymenko** [comment]
Hi @monstrege unfortunately I will be able to look into this issue not earlier then Saturday :-(

**Comment by AlexKhymenko** [comment]
Fixed in version 8.0.0
