### ISSUE TITLE
NgxPermissionsRouterData

### ISSUE THREAD

**Issue by AtefMlaouhi** [AlexKhymenko/ngx-permissions#132]
## NgxPermissionsRouterData Bug

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

when I use [NgxPermissionsGuard](https://github.com/AlexKhymenko/ngx-permissions#usage-with-routes)
if data passed in route is null | undefined | Empty String
the check pass
```typescript
  {
    path: 'somePath',
    component: someComponenet,
    loadChildren: () => import('someModule').then((module) => module.SomeModule),
    canActivate: [NgxPermissionsGuard],
    data: {
      permissions: {
        only: null | ''
      }
    }
  },

private transformPermission => ???
```

## Environment

<pre>

<code>
Angular version: 9.0.2
ngx-permissions version: 7.0.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Hi @AtefMlaouhi  working as intended. Cause If you don't specify permissions that are allowed then everything is allowed. :-)
