### ISSUE TITLE
When to use getPermission() or hasPermission()?

### ISSUE THREAD

**Issue by Lempkin** [AlexKhymenko/ngx-permissions#133]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior
I didn't find some advice about how to use the getPermission() or hasPermission()? What's the differences between each other and when should we use one or the other?

## Environment

<pre><code>
Angular version: 8.1.3
ngx-permissions version: 7.0.3

**Comment by AlexKhymenko** [comment]
Hi @Lempkin  hasPermission will return boolean if it has permission or not.
getPermission will return permission object with all permissions that You have
