### ISSUE TITLE
Setting Permission in template

### ISSUE THREAD

**Issue by weilies** [AlexKhymenko/ngx-permissions#134]
I would like to clarify what's the proper sample code if i would like to implement role-permission based security control in my template. I have no problem running the code WITHOUT roles. I could show/hide template sections with permissions.

But things start to confuse, correct me if i am wrong, we can still set 'canSomeAction' in template even we introduce roles, right? 
What's happened to me, following code never work
```
    this.rolesServices.addRole("EMPLOYEE", ["addCompany", "configPay"]);

... template
<ng-template [ngxPermissionsOnly]="['addCompany']">
  addCompany...
</ng-template>
```

The working codes are below 

```
    this.permissionsService.addPermission(["EMPLOYEE"]);
    this.rolesServices.addRole("EMPLOYEE", ["addCompany", "configPay"]);
```

Templates
```
<ng-template permissions [ngxPermissionsOnly]="['EMPLOYEE', 'MARY']">
  Self Service ...
</ng-template>
<ng-template [ngxPermissionsOnly]="['addCompany']">
  addCompany...
</ng-template>
```

Actual Output:
Self Service ...

Expected Output:
```
Self Service ...
addCompany...
```

Why do we need to execute this.rolesServices.addRole as addCompany, configPay cannot work if i dont register them under addPermission? My understanding roles are consolidation of permissions. So isn't following code is just enough?
`this.rolesServices.addRole("EMPLOYEE", ["addCompany", "configPay"])`
... template
```
<ng-template [ngxPermissionsOnly]="['addCompany']">
  addCompany...
</ng-template>
```

There are scenarios we need more vibrant controls like 'can<someActions><someComponent>' and we need to put them in template, instead of just simply put [ngxPermissionsOnly]="EMPLOYEE". Which is hard to expand.

## Environment

<pre><code>
Angular version: 9.1
ngx-permissions version: 7.0.3

Browser: Chrome Desktop v81

**Comment by AlexKhymenko** [comment]
Hi @weilies I understand this can be confusion. Just think of roles as 'and' operator(so when You specify Employee roles it means that user should have addCompany and config pay to see whats inside. 
`this.rolesServices.addRole("EMPLOYEE", ["addCompany", "configPay"])
`
To make it work 
```
   this.permissionsService.addPermission( ["addCompany", "configPay"]);
   this.rolesServices.addRole("EMPLOYEE", ["addCompany", "configPay"]);
```

All the set up is done in permissions. I understand this can be a little bit confused. I will better explain in wiki cause it gets people frustrated. If You have more question let me know :-)

**Comment by weilies** [comment]
hi @AlexKhymenko , i am extremely fine to add both 'addPermission' + addRole' in the code. Even they look redundant but i am completely fine with that.
With your sample code it look clearer. Thanks!

**Comment by weilies** [comment]
Just to share how i designed my security matrix, it makes me understand easier without introduce/implement your 'role'. When the accesses initiate, i will pump in a ROLE after user logged in. 

```
  initialize(role: string, modules: any) {
    console.log('init access, ', role)
    let accesses = [];
    
    switch (role.toLowerCase()) {
      case "employee":
        accesses.push('ESS-attendance', 'ESS-claim', 'ESS-leave', 'ESS-payroll')
      break;
      case "operator":
        accesses.push('ESS-attendance', 'ESS-claim', 'ESS-leave', 'ESS-payroll')
        accesses.push('OPS-attendance', 'OPS-claim', 'OPS-leave', 'OPS-payroll')
      break;
      case "client":
        accesses.push('ESS-attendance', 'ESS-claim', 'ESS-leave', 'ESS-payroll')
        accesses.push('OPS-attendance', 'OPS-claim', 'OPS-leave', 'OPS-payroll')
        accesses.push('OPS-attendance', 'ADM-claim', 'ADM-leave', 'ADM-payroll')
        accesses.push('ADM-core') 
      break;
      case "superuser":
        accesses.push('ESS-attendance', 'ESS-claim', 'ESS-leave', 'ESS-payroll')
        accesses.push('OPS-attendance', 'OPS-claim', 'OPS-leave', 'OPS-payroll')
        accesses.push('OPS-attendance', 'ADM-claim', 'ADM-leave', 'ADM-payroll')
        accesses.push('ADM-core', 'SYS-core') // default for superuser
      break;
    }

      this.permissions.addPermission(accesses)
  }
```

Hence, there ain't a need for me to execute addRole in my use case.
Thanks!

**Comment by AlexKhymenko** [comment]
@weilies Thanks for sharing!!!. It will help someone to Use Your solution :-)
