### ISSUE TITLE
Generic type 'ModuleWithProviders<T>' requires 1 type argument(s) - Error.

### ISSUE THREAD

**Issue by SagarKapasi099** [AlexKhymenko/ngx-permissions#137]
## I'm submitting a Bug Report

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

<code>
<pre>
ERROR in node_modules/ngx-permissions/lib/index.d.ts:21:58 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

21     static forRoot(config?: NgxPermissionsModuleConfig): ModuleWithProviders;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~~~~~~~~~~~~~~~~~~~
node_modules/ngx-permissions/lib/index.d.ts:22:59 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

22     static forChild(config?: NgxPermissionsModuleConfig): ModuleWithProviders;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~~~~~~~~~~~~~~~~~~~
</pre>
</code>

## Expected behavior

ModuleWithProviders Should Have Generic Type Defined. Should Have No Generic Error.

Seems like bug is fixed, but not released.
(Line 51) https://github.com/AlexKhymenko/ngx-permissions/blob/48892d6be4ca7cf07821a160fe142420025e2c7c/projects/ngx-permissions/src/lib/index.ts

## Minimal reproduction of the problem with instructions

Breaks A New Angular 10 Project.

## Environment

<pre><code>
Angular version: 10.0.2
ngx-permissions version: 7.0.3

<pre>
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.0
Node: 12.14.1
OS: win32 x64

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: <error>

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.0
@angular-devkit/build-angular      0.1000.0
@angular-devkit/build-optimizer    0.1000.0
@angular-devkit/build-webpack      0.1000.0
@angular-devkit/core               10.0.0
@angular-devkit/schematics         10.0.0
@angular/cdk                       10.0.1
@angular/cli                       10.0.0
@angular/material                  10.0.1
@angular/material-moment-adapter   10.0.1
@ngtools/webpack                   10.0.0
@schematics/angular                10.0.0
@schematics/update                 0.1000.0
rxjs                               6.5.5
typescript                         3.9.5
webpack                            4.43.0
</pre>

Browser: Error is not browser specific

**Comment by AlexKhymenko** [comment]
@SagarKapasi099 Will be fixed on Saturday. Or maybe somebody will create pr before :-)

**Comment by SagarKapasi099** [comment]
Actually the code looks like it is fixed.
Please have a look at (Line 51) https://github.com/AlexKhymenko/ngx-permissions/blob/48892d6be4ca7cf07821a160fe142420025e2c7c/projects/ngx-permissions/src/lib/index.ts

**Comment by AlexKhymenko** [comment]
@SagarKapasi099 Fixed in version 8.0.0
