### ISSUE TITLE
Function in *ngxPermissions no longer works on angular 10

### ISSUE THREAD

**Issue by BrkCoder** [AlexKhymenko/ngx-permissions#138]
## I'm submitting a...

<pre><code>
[ X ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
when placed a function into *ngPermissionsOnly input, the entire app is frozen and not applicable. 

## Expected behavior
*ngPermissionsOnly should take string, string[], and function as documented.

## Minimal reproduction of the problem with instructions
https://angular-ivy-s2gkhn.stackblitz.io

## Environment

<pre><code>
Angular version: 10
ngx-permissions version: 7.0.3

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by BrkCoder** [comment]
Please handle this asap, your library doesn't suitable for prod environments at all. this issue also happen in angular 9 , 8

**Comment by AlexKhymenko** [comment]
@BrkCoder where did You find that You can put function inside *ngxPermissionsOnly ?

**Comment by AlexKhymenko** [comment]
https://github.com/AlexKhymenko/ngx-permissions/wiki/Controlling-access-in-views it only accept string or string[]? maybe the result of the function that is string or string[]

**Comment by BrkCoder** [comment]
I remember correctly that it work with functions also...
![image](https://user-images.githubusercontent.com/5408870/86376883-53796a80-bc90-11ea-97f8-995809b298e9.png)

**Comment by BrkCoder** [comment]
> https://github.com/AlexKhymenko/ngx-permissions/wiki/Controlling-access-in-views it only accept string or string[]? maybe the result of the function that is string or string[]

yes the result of the function is a string or string array...

**Comment by AlexKhymenko** [comment]
The chapter that You send is from routes not from directive.
Its very diffucult to say whats wrong without seeing the code. The link doesn't work for some reason
