### ISSUE TITLE
Issue on refresh page with Implemented Guards

### ISSUE THREAD

**Issue by joelmuskwe** [AlexKhymenko/ngx-permissions#14]
I have the following issue i save my jwt token in the local storage now on page refresh i am retrieving the users permissions and roles from an api but it seems the guard is firing before the permissions and roles have been loaded. so my question is how can i wait for the roles and permissions to be resolved before firing the NgxPermissionsGuard

**Comment by AlexKhymenko** [comment]
You can use this approach https://github.com/AlexKhymenko/ngx-permissions/wiki/common-use-cases-router

**Comment by AlexKhymenko** [comment]
Or this one https://github.com/AlexKhymenko/ngx-permissions/wiki/Managing-permissions#to-load-permissions-before-application-start-up but i recomment google APP_INITIALIZER for better understanding.

**Comment by joelmuskwe** [comment]
Have you ever tried it with a redux implementation like NGRX. on page reload i send a LOAD_USER action to retrieve user details.

**Comment by AlexKhymenko** [comment]
The problem is you probably do it from component. When the application is already loaded. You need to do it before the application loads. maybe this will helps https://toddmotto.com/preloading-ngrx-store-route-guards

**Comment by joelmuskwe** [comment]
thanks let me take a look at it
