### ISSUE TITLE
rxjs_Observable.Observable.merge(...).mergeAll(...).first(...).toPromise is not a function

### ISSUE THREAD

**Issue by morozenkomv** [AlexKhymenko/ngx-permissions#15]
Hi!
I have this error after update angular version

TypeError: rxjs_Observable.Observable.merge(...).mergeAll(...).first(...).toPromise is not a function
    at NgxPermissionsService.hasArrayPermission (ngx-permissions.umd.js:211)
    at NgxPermissionsService.hasPermission (ngx-permissions.umd.js:115)
    at NgxPermissionsDirective.validateOnlyPermissions (ngx-permissions.umd.js:471)
    at SafeSubscriber._next (ngx-permissions.umd.js:433)
    at SafeSubscriber.__tryOrSetError (vendor.js?v=al17c1S52F9ckakALoRfjx9ZZ0m1LMiMq-rrE1oO-GM:10843)
    at SafeSubscriber.next (vendor.js?v=al17c1S52F9ckakALoRfjx9ZZ0m1LMiMq-rrE1oO-GM:10783)
    at Subscriber._next (vendor.js?v=al17c1S52F9ckakALoRfjx9ZZ0m1LMiMq-rrE1oO-GM:10721)
    at Subscriber.next (vendor.js?v=al17c1S52F9ckakALoRfjx9ZZ0m1LMiMq-rrE1oO-GM:10685)
    at SkipSubscriber._next (skip.js:53)
    at SkipSubscriber.Subscriber.next (vendor.js?v=al17c1S52F9ckakALoRfjx9ZZ0m1LMiMq-rrE1oO-GM:10685)

Have somebody any ideas to resolve this issue?

## Environment

<pre><code>
Angular version: 5.1.0-rc.1
ngx-permissions version: ^3.0.0

Browser:
- [x] Chrome (Android) version XX

**Comment by AlexKhymenko** [comment]
What is the version of rxjs library ??

**Comment by morozenkomv** [comment]
5.5.1

**Comment by AlexKhymenko** [comment]
I will recheck tommorow. But for quick fix just add manually operators(first mergeAll, toPromise) to you polyffils file.

**Comment by AlexKhymenko** [comment]
Or try to upgrade to latest version

**Comment by AlexKhymenko** [comment]
there was bug fixed in 5.5.2 package: fixed import failures in Webpack (#2987) (e16202d)

**Comment by morozenkomv** [comment]
Thanks, I'll try.

**Comment by morozenkomv** [comment]
This issue was fixed by refresh webpack manifest.
Issue can be closed.

**Comment by AlexKhymenko** [comment]
@jrmlstf it can be due to some problem in cli. I have tried everything works.

**Comment by jrmlstf** [comment]
You were right @AlexKhymenko , the pbm came from @angular/cli. More precisely from build-optimizer. When switched off, error is gone. It probable removes some Rxjs code.

**Comment by Spardevil** [comment]
Hi @jrmlstf , I have the same problem, what exactly you did to solve it ?

**Comment by jrmlstf** [comment]
@Spardevil Build without build optimizer : `ng build --prod --build-optimizer=false`

**Comment by Spardevil** [comment]
@jrmlstf Thanks, it works. I do understand that it's a cli problem, but anyway, it would be great to see it working with optimizer, eventually, it removes some unnecessary code, so I would like to see it enabled.

**Comment by AlexKhymenko** [comment]
@Spardevil @jrmlstf Have quick fix that worked for me 

Add hard version to package json
```
 "@angular-devkit/build-optimizer": "0.0.36",
    "@angular-devkit/schematics":"0.0.42",
    "@angular-devkit/core": "0.0.23"
```

And my build script is 

`node --max-old-space-size=4096 ./node_modules/@angular/cli/bin/ng build --aot --build-optimizer=true --output-hashing none`

And waiting for official fix :-)

**Comment by eugenzor** [comment]
I have the same problem (cli 1.6.5 is being used)

```
    "@angular-devkit/build-optimizer": "0.0.36",
    "@angular-devkit/schematics":"0.0.42",
    "@angular-devkit/core": "0.0.23"
```
didn't help

Does it mean that any Observable.merge is not working for the prod builds with --build-optimizer?

**Comment by AlexKhymenko** [comment]
Yes. Just happens that ngx-permissions usually the first library thats getting on the way :-) Have you tried to add --output-hashing none ?

**Comment by eugenzor** [comment]
Sorry `--output-hashing none` didn't help (don't think it affects any logic inside)

**Comment by AlexKhymenko** [comment]
@eugenzor This one worked for me rxjs 5.5.0 added import 'rxjs/add/observable/merge';
 and import 'rxjs/add/operator/merge';
to polifylls.ts

**Comment by devakone** [comment]
Running into the same error even with the imports added to `polyfills.ts`

**Comment by AlexKhymenko** [comment]
@devakone what is the version of rxJs. Can You try with the version 5.5

**Comment by devakone** [comment]
I am on 5.5.6

**Comment by AlexKhymenko** [comment]
@devakone do you have error with 5.5.0 ?

**Comment by devakone** [comment]
Yes i have a build error with 5.5.0 
```Module not found: Error: Can't resolve 'rxjs/operators/map'```
but unlike the one we're talking about in this issue, this one is at build time. I think that's the error that you mentioned was fixed in 5.5.2

**Comment by AlexKhymenko** [comment]
@devakone try with 5.5.2 also what version of cli you are using?

**Comment by devakone** [comment]
for cli I am on 1.6.4. I'll try with 5.5.2 and report the result in a few

**Comment by devakone** [comment]
It did work with RxJS 5.5.24. That is the craziest thing, you would think that any higher patch version would work.
