### ISSUE TITLE
redirectTo not working

### ISSUE THREAD

**Issue by quan1997ap** [AlexKhymenko/ngx-permissions#150]
Hi dev team.  I try use your library in my project and config like image below.
But it only work when user has true permission ( loaded before ). When change another permission ( not loaded before ). It not redirect to error path.
I dont know what's a reason. Can u help me!
Thanks all.

I am using
"ngx-permissions": "^8.1.1",
angular 10

![image](https://user-images.githubusercontent.com/38683698/94386728-8b4e5c00-0172-11eb-9bea-1f736d8b4cec.png)

**Comment by AlexKhymenko** [comment]
@quan1997ap the library uses https://angular.io/api/router/Router#navigate under the hood. Can You navigate with this function ?

**Comment by AlexKhymenko** [comment]
Hi think this is resolved? If no please reopen issue
