### ISSUE TITLE
has permission function always returns false , but the directive returns true 

### ISSUE THREAD

**Issue by ammar-esrawi** [AlexKhymenko/ngx-permissions#152]
<pre><code>
evaluateCP(perms, attrName) {
    this.permissionsService.
    
    hasPermission(perms).then(
      v =>{
        this.calculatedPermissions[attrName] = v; //v always false but *ngxPermissionsOnly renders the view 
        console.log(v);
      } 

    );
  }
</code></pre>

I am unable to use *ngxPermissionsOnly  cuz inside a metsmenu ul the *ngxPermissionsOnly  breaks the nested menu 

it looks like the ngxPermissionsOnly  directive rerneders the element without the listeners 
`
<ul metis-menu appSpy toggle="false" class="metismenu side-nav">

            <li class="side-nav-title side-nav-item">Navigation</li>

           
                <li class="side-nav-item" appSpy *ngxPermissionsOnly="permissions.adminSidebar">
                    <a href="javascript: void(0);" class="side-nav-link">
                        <i class="uil-cog"></i>
                        <span>Adminstration</span>
                        <span class="menu-arrow"></span>
                    </a>
                    <ul class="side-nav-second-level" aria-expanded="false">
                        <li [routerLinkActive]="['mm-active']">
                            <a [routerLink]="['/adminstration']" href="javascript:void(0);">Dashboard</a>
                        </li>
                        <li [routerLinkActive]="['mm-active']" *ngxPermissionsOnly="permissions.listParams">
                            <a [routerLink]="['/system-params']" href="javascript:void(0);">System Parameters</a>
                        </li>
                        <li [routerLinkActive]="['mm-active']" *ngxPermissionsOnly="permissions.listUsers">
                            <a [routerLink]="['/user-list']" href="javascript:void(0);">Users</a>
                        </li>
                        <li [routerLinkActive]="['mm-active']" *ngxPermissionsOnly="permissions.createUser">
                            <a [routerLink]="['/user-details']" href="javascript:void(0);">Create User</a>
                        </li>
                        <li [routerLinkActive]="['mm-active']" *ngxPermissionsOnly="permissions.listRoles">
                            <a [routerLink]="['/role-list']" href="javascript:void(0);">Roles</a>
                        </li>
                        <li [routerLinkActive]="['mm-active']" *ngxPermissionsOnly="permissions.createRole">
                            <a [routerLink]="['/role-details']" href="javascript:void(0);">Create Role</a>
                        </li>
                        <li [routerLinkActive]="['mm-active']" *ngxPermissionsOnly="permissions.listPG">
                            <a [routerLink]="['/pg-list']" href="javascript:void(0);">Permissions</a>
                        </li>
                        <li [routerLinkActive]="['mm-active']" *ngxPermissionsOnly="permissions.createPG">
                            <a [routerLink]="['/pg-details']" href="javascript:void(0);">Create Permission</a>
                        </li>
                    </ul>
                </li>
      </ul>
`

**Comment by AlexKhymenko** [comment]
H @ammar-esrawi i. What version are You using? And it would be very nice If You can create reproduction

**Comment by AlexKhymenko** [comment]
If You have problems please reopen it :-) Thank You :-)
