### ISSUE TITLE
Create directive ngxPermissionsOnlyAll to validate that you have ALL the rules

### ISSUE THREAD

**Issue by abalad** [AlexKhymenko/ngx-permissions#153]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

I would like to specify multiple permissions that the user needs to have in order to complete an action. The issue is that he needs to have all permissions not just one of them, so the logic needs to be "and" not "or".

## Expected behavior

```html
<div *ngxPermissionsOnlyAll="['Read', 'Write']">
    <div>You can see this text </div>
</div>
```

## Environment

<pre><code>
Angular version: 10.0.0
ngx-permissions version: 8.0.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
@abalad Hi its possible with roles roles use and operator 
```
 ngxRolesService
  .addRole('ADMIN', ['read', 'write']);
```

And then just use 
```

<div *ngxPermissionsOnly="['ADMIN']">
    <div>You can see this text </div>
</div>
```

If the user doesnt have read and write it will not show.
