### ISSUE TITLE
How can we give access to user on having only two specific permissions

### ISSUE THREAD

**Issue by ManojKuma007** [AlexKhymenko/ngx-permissions#154]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z
ngx-permissions version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Hi @ManojKuma007 there is not enough information to give you advice. Maybe You can find it in documentation https://github.com/AlexKhymenko/ngx-permissions/wiki. Have a nice day.
