### ISSUE TITLE
addRolesWithPermissions not emitting roles$ Observable

### ISSUE THREAD

**Issue by faradoxuz** [AlexKhymenko/ngx-permissions#155]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

After adding roles 
`this._roleService.addRolesWithPermissions(obj);`
$roles.subscribe() not working

## Expected behavior

$roles.subscribe() must work

**Comment by AlexKhymenko** [comment]
Hi @faradoxuz can You create reproduction. It would speed up fixing ?

**Comment by faradoxuz** [comment]
Hi @AlexKhymenko , stackblitz?

**Comment by AlexKhymenko** [comment]
Would be nice

**Comment by faradoxuz** [comment]
oh, sorry @AlexKhymenko, my bad :), i had an error before adding the role, you can close this issue.

**Comment by faradoxuz** [comment]
anyway, this is the stackblitz 
https://stackblitz.com/edit/angular-ivy-1qqjd2

**Comment by AlexKhymenko** [comment]
@faradoxuz No problems. Have a great day :-) Thanks for stackblitz!!

**Comment by faradoxuz** [comment]
Thank you for great library
