### ISSUE TITLE
Error with shared module approach

### ISSUE THREAD

**Issue by markosimulak** [AlexKhymenko/ngx-permissions#158]
Hi :)

I tried to isolate `NgxPermissionsModule` into SharedModule. 
Then I tried to use `NgxPermissionsService` in my `app.component.ts`, but I got an error:

![image](https://user-images.githubusercontent.com/21991764/107203058-38779180-69fb-11eb-8348-d5fe1690c2d5.png)

I tried to fixed that error by adding `NgxPermissionsService` in `SharedModule` providers  but then I got second error:

![image](https://user-images.githubusercontent.com/21991764/107203334-97d5a180-69fb-11eb-9697-31f5aa14f9c2.png)

Finally, when I added `NgxPermissionsModule.forRoot()` in `SharerdModule` error gone.
But from documentation I saw...

![image](https://user-images.githubusercontent.com/21991764/107203574-e6833b80-69fb-11eb-8324-b95b90546c69.png)

So does anyone know how to solve this issue?

**Comment by AlexKhymenko** [comment]
So basically add forRoot in Your main module. and without forRoot in Your shared module. And everything will be working as intented

**Comment by markosimulak** [comment]
Ok, thanks!
