### ISSUE TITLE
Usage of roles

### ISSUE THREAD

**Issue by dharapvj** [AlexKhymenko/ngx-permissions#16]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior
Currently, I do not understand the value of using roles. All directives, guards work on concept of permissions only.

May be I am missing some critical information. Hope to understand the same better. e.g. I can get role and permissions object from backend system. I am able to create roles and corresponding permissions using the APIs described. But can I really use roles in the system? I am right now not sure.. because usage of roles in templates, guards etc is not clearly explained at the moment.

## Expected behavior

Clear example or documentation on using roles. I am hoping that roles would allow me a shortcut in same directive / guards to specify 10 different permissions.

**Comment by AlexKhymenko** [comment]
The main difference role uses 'and' operator. So for example admin (write and read permissions) if user doesnt have one of them it will not show. With this api you can do anything you want so for example you can write your own permission that will use some custom logic :-) I will update documentation after holidays :-)

**Comment by misaizdaleka** [comment]
+1 here

Some code in Plunker is very, very confusing:
```
this.roleService.addRole('GUEST', ["ADMIN"])
```

Here you're defining a role name _GUEST_ with a permission named _ADMIN_??? Didn't you say in the docs that _It's a good convention to start permission with a verb and combine them with resource or object_???

**Comment by misaizdaleka** [comment]
`NgxPermissionsService.removePermission('user');`

Again, the convention you mentioned says to _start permission with a verb and combine them with resource or object_.

**Comment by AlexKhymenko** [comment]
@misaizdaleka Kind of yes but it really depends how your  backend service is sending you data.
For example usage of roles is when you have a lot of permissions and you want to combine them. But usually backend just uses admin, guest as permissions and not like roles then using just permissions service is enough.
