### ISSUE TITLE
NgxPermissionsGuard : multiple mandatory permissions

### ISSUE THREAD

**Issue by Lempkin** [AlexKhymenko/ngx-permissions#164]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

When setting only Array of permissions, user should have one of the permissions to be allowed.

## Expected behavior

To have a way to list multiple mandatory permissions to be allowed, so that user must have every permissions to be allowed.

## Environment

<pre><code>
Angular version: X.Y.Z
ngx-permissions version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Hi @Lempkin  You can actually achieve it in 2 ways. First one create custom permission and specify what You want there'
 ```
this.permissionsService.addPermission('andOperator', (permissionName, permissionsObject) => {
        return !!permissionsObject["ADMIN"] && !!permissionsObject["user"];
    });
```

Or you can create role

`NgxRolesService
  .addRole('andOperator', ['ADMIN', 'USER']);`

And use in tempalte 

`<div *ngxPermissionsOnly="['andOperator']">`

**Comment by Lempkin** [comment]
Hi thx for your answer but I mean for route control, with the NgxPermissionGuard, like :
```
canActivate: [NgxPermissionsGuard],
    data: {
      permissions: {
        only: [PERMISSION.PERM1, PERMISSION.PERM2],
        redirectTo: FORBIDDEN_ROUTE,
      }
    }
```

For now, user will be allowed if he has perm1 OR perm2. I would like to be able to specify that he should have perm1 AND perm2

**Comment by AlexKhymenko** [comment]
@Lempkin You can achive the same in route

canActivate: [NgxPermissionsGuard],
    data: {
      permissions: {
        only: ['andOperator'],
        redirectTo: FORBIDDEN_ROUTE,
      }
    }

**Comment by Lempkin** [comment]
Hi, thx for your answer but that means that I have to create a role for every combination that I need to protect the routes. Would be more handy to be able to combine it into an array in routes data

**Comment by AlexKhymenko** [comment]
@Lempkin What Do You think good api will look for this feature?

**Comment by AlexKhymenko** [comment]
Sorry for very late response. This can be achived by creating Your own guard and extending ngxPermissionsGuard
