### ISSUE TITLE
Angular 11 Support

### ISSUE THREAD

**Issue by blindsz** [AlexKhymenko/ngx-permissions#166]
Hi, whencan we expect angular 11 support?

**Comment by AlexKhymenko** [comment]
Hi @blindsz its actually supports angular 11 already

**Comment by blindsz** [comment]
I think this would cause a warning of peer dependencies.

**Comment by AlexKhymenko** [comment]
@blindsz Yes I will update a little bit later so overload right now. Thank You for bringing it.

**Comment by blindsz** [comment]
> @blindsz Yes I will update a little bit later so overload right now. Thank You for bringing it.

No worries! Thanks!
