### ISSUE TITLE
Whether I can give variables here without hardcoding the permissions for routes?

### ISSUE THREAD

**Issue by sruthivarghese15** [AlexKhymenko/ngx-permissions#17]
let routes = [
  { path: '', 
    canActivate: [AuthGuard],
    children: [
      {path: 'component', 
      component: ComponentName, 
      canActivate: [NgxPermissionsGuard],
      data: {
         permissions: {
           only: ['ADMIN', 'MODERATOR'],
           redirectTo: 'another-route'
         }
       }}
    ]
  }
]
Here you've hardcoded the permissions only for the routes right? But I want to take the details from the database. Is there any way to load that?

**Comment by AlexKhymenko** [comment]
I don't fully understand your use case. But you can specify like custom permissions and then pass a function into it with custom logic you need(make a call and then write custom logic depending what will return).

**Comment by sruthivarghese15** [comment]
Like here you are permissions only to ADMIN and MODERATOR right? What if I want to get the details from the database?

**Comment by AlexKhymenko** [comment]
You can make call to the database  


```
 this.permissionsService.addPermission('callToDatabase', (permissionName, permissionsObject) => {
      return this.databaseService.makeCall().toPromise().then((data) => {
       //write your custom logic here
         })
    });

```

**Comment by sruthivarghese15** [comment]
That thing I'm doing after login, adding the permissions.  But what if I need to restrict the access to the routes?

**Comment by AlexKhymenko** [comment]
the same way. But probably what you are looking for is  load permissions before your application starts.
