### ISSUE TITLE
NgxPermissionsService loosing data on page refresh

### ISSUE THREAD

**Issue by xts-velkumars** [AlexKhymenko/ngx-permissions#173]
Hi, I'm setting the permissions from Login Component like below. 

**Login Component** 
```
loadPermissions(roleName: string) {
        let permissions = [];
        permissions.push(roleName);
        this.permissionsService.loadPermissions(permissions);
    }
```

On the successful login, page will be redirected to Dashboard page.
I'm doing console to check the permission ngOnInit. I'm getting the data as excepted.

> **If I refresh the page, I have lost my data. How I can resolve this?**

**Dashboard Component**

```
  ngOnInit() {
        var permissions = this.permissionsService.getPermissions();
        console.log(permissions);
    }
```
**Before refresh** 

![image](https://user-images.githubusercontent.com/13570225/118868613-04691200-b902-11eb-85ee-d3445d6e6c79.png)

**After refresh**

![image](https://user-images.githubusercontent.com/13570225/118868712-22367700-b902-11eb-8dfd-456e747961a7.png)

**Comment by bikerp** [comment]
I'm facing the same issue. Do you have any suggestion how to fix it?

**Comment by AlexKhymenko** [comment]
Hi its because angular looses all data on refresh. One suggestion for fix is described in wiki https://github.com/AlexKhymenko/ngx-permissions/wiki/common-use-cases#save-permissions-on-page-refresh
