### ISSUE TITLE
how to set default value for redirectTo

### ISSUE THREAD

**Issue by khodabandelu** [AlexKhymenko/ngx-permissions#178]
how can i set Default value for redirectTo in NgxPermissionsGuard.

**Comment by AlexKhymenko** [comment]
@timhoekstra This is great idea. Will look into it

**Comment by AlexKhymenko** [comment]
@khodabandelu @timhoekstra What do You think, is it ok If You still have to specify redirectTo object (even empty) ?

```
 permissions: {
        only: 'ADMIN1',
          redirectTo: {}
      } as NgxPermissionsRouterData
```

This is use case when in the project You just want to block user coming to page, not to redirect him somewhere

**Comment by khodabandelu** [comment]
i need default value for all canload and canActivate to redirect to page 403 so that I dont have to duplicate redirecTo option to set page 403 for permission exception whereever i use NgxPermissionGuard .

for solve this problem i have to create own permmissionGuard and override NgxPermissionsRouterData before call NgxPermissionGuard methods.

my own Guard that I use NgxPermissionsGuard methods to support this feature.

```typescript
@Injectable({providedIn: 'root'})
export class PermissionsGuard implements CanActivate {

	constructor(private ngxPermissionsGuard: NgxPermissionsGuard, private authService: AuthService) {
	}

	canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Promise<boolean> | boolean {
		if (route && route.data && route.data.permissions as NgxPermissionsRouterData && route.data.permissions.redirectTo == undefined) {
			route.data.permissions.redirectTo = '/error/error-403';
		}
		if (!this.checkAuth()) {
			return false
		} else {
			return this.ngxPermissionsGuard.canActivate(route, state);
		}
	}

	canLoad(route: Route): boolean | Observable<boolean> | Promise<boolean> {
		if (route && route.data && route.data.permissions as NgxPermissionsRouterData && route.data.permissions.redirectTo == undefined) {
			route.data.permissions.redirectTo = '/error/error-403';
		}
		if (!this.checkAuth()) {
			return false
		} else {
			return this.ngxPermissionsGuard.canLoad(route);
		}
	}


	checkAuth() {
		const currentUser = this.authService.currentUserValue;
		if (currentUser) {
			// logged in so return true
			return true;
		}

		// not logged in so redirect to login page with the return url
		this.authService.logout();
		return false;
	}

}
```

**Comment by timhoekstra** [comment]
> This is use case when in the project You just want to block user coming to page, not to redirect him somewhere

Do you mean having to specify it on every route as empty?

I would expect the following:
```
defaultRedirectTo specified, no redirectTo on route -> defaultRedirectTo triggers
defaultRedirectTo specified, redirectTo on route -> redirectTo on route triggers
```

If you want to keep the option open to block the incoming user then yes I think it's a good idea to be able to specify an empty object to block the user either as the defaultRedirectTo or the route redirectTo.

I would like to remark that in the meantime I have also taken the approach of @khodabandelu and created a new guard that forwards the canActivate etc. calls to NgxPermissionsGuard and put some default behavior in there. That also solves the problem.

**Comment by AlexKhymenko** [comment]
@timhoekstra @khodabandelu After careful thinking its much better to add Your code to the documentation so it will be easier for people to create their own custom guard.It will solve more problems. Thank You for helping!
