### ISSUE TITLE
View restriction permissions break on refresh

### ISSUE THREAD

**Issue by gantrim** [AlexKhymenko/ngx-permissions#18]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
`ngxpermissionsOnly` shows an element on the first page load, but that item is hidden when the page is refreshed or when you navigate away from a page and then back again.
## Expected behavior

`ngxPermissionsOnly` should show and hide elements consistently regardless of page refresh and navigation

## Minimal reproduction of the problem with instructions

1. Load permissions using `addPermission` or `loadPermissions`
2. Use `ngxPermissionsOnly` directive in a view to show or hide an element
3. Navigate to page using `ngxPermissionsOnly` --> Element is shown since user has correct permissions
4. Refresh page
5. Now element is hidden even though user has permissions

Code:
auth.service.ts:
```typescript
export class AuthService {
	constructor(private ngxPermissionsService: NgxPermissionsService) {
		//...
	}

	//Function called after a user logs in
	public afterSignIn() {
		const permissionNames = ["create-contract", "create-payment", "create-prospect", "modify-contract", "modify-invoiced", "modify-prospect", "modify-quickbooks-reference-id", "modify-sales-actions"];

		// Always return true for testing purposes
		this.ngxPermissionsService.addPermission(allFrontendPermissionNames, (permissionName, permissionStore) => {
			return true;
		});

		//redirect to home component
	}
}
```
home.component.ts
```html
<ng-template [ngxPermissionsExcept]="['modify-sales-actions', 'create-contract']">
	<div class='row'>
		<div class='col-sm-12'>
			<h1> Perms Test </h1>
		</div>
	</div>
</ng-template>
```
## Environment

<pre><code>
Angular version: 4.0.0
ngx-permissions version: 3.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
The problem is on refresh the whole application restarts and looses data. So its better to store permissions in localStorage and then load them.

**Comment by gantrim** [comment]
Thank you for the reply. I probably should have tried localStorage.  Angular does allow for persisting data at the service level without depending on local storage though, so it may be something to look into in the future. For now however it might be enough to just update your examples to show or mention the usage of localStorage.

**Comment by AlexKhymenko** [comment]
Hi services doesnt allow this :-) https://stackoverflow.com/questions/42249005/angular-2-persistent-data-storage-on-refresh-or-rerouting-to-external-urls-and-b 
on the second parth will update as soon as i can :-)
