### ISSUE TITLE
Rolebased access for elements and side bars

### ISSUE THREAD

**Issue by nidhinkumar06** [AlexKhymenko/ngx-permissions#186]
How to set role-based access for side nav and elements in Angular using Ngx-permissions

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior
I have been looking at the Ngx-permissions library and tried to implement it for role-based access like the below implementation to show/hide a button based on the user role.

app.component.ts

```
this.permissionService.addPermission(['SUPER_ADMIN']);
this.roleService.addRolesWithPermissions({
  SUPER_ADMIN : ['canViewDashboard', 'canAddOrganization', 'canViewOrganization', 'canEditOrganization'],
  PARK_ADMIN: ['canViewDashboard', 'canViewOrganization', 'canEditOrganization']
});
```
HTML File

```
<button
    *ngxPermissionsOnly="'canAddOrganization'"
    class="btn btn-outline-primary float-right py-0 pl-1 rounded-pill d-flex align-items-center"
    routerLink="./add">
    <i class="fs-2 fa fa-plus-circle" aria-hidden="true"></i>
    <span class="ml-1">Organization</span>
  </button>
```
When i run the above snippet it shows the organization button for a role that doesn't have access to it. Say for example if SuperAdmin logs in it show the AddOrganization button.
but if the ParkAdmin logs in it show the Add Organization button but in an ideal scenario, it shouldn't show it.

But here i am confused that how does Ngx-Permission know the logged-in user role? 

Similarly, i would like to know how do we set permissions for nav.ts files like below

```
export const navItems: NavItems[] = [
  {
    name: 'Dashboard',
    url: '/dashboard',
    icon: 'fa fa-tachometer',
  },
  {
    name: 'Parks',
    url: '/parks',
    icon: 'fa fa-map-marker',
  },
  {
    name: 'Park Admins',
    url: '/park_admin',
    icon: 'fa fa-user-secret',
  },
  {
    name: 'Organizations',
    url: '/organizations',
    icon: 'fa fa-building',
  },
];
```

## Environment

<pre><code>
Angular version: 11.2.5
ngx-permissions version: 8.1.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Hi @nidhinkumar06 You are setting permissions with this line 

`this.roleService.addRolesWithPermissions({
  SUPER_ADMIN : ['canViewDashboard', 'canAddOrganization', 'canViewOrganization', 'canEditOrganization'],
  PARK_ADMIN: ['canViewDashboard', 'canViewOrganization', 'canEditOrganization']
});`

so they are in the app

You can use just addRole and then load permissions to the application

**Comment by nidhinkumar06** [comment]
@AlexKhymenko  So in the load permission, we have to use like below right?

```
this.permissionService.loadPermission(['SUPER_ADMIN', 'PARK_ADMIN']);
```

**Comment by AlexKhymenko** [comment]
@nidhinkumar06 it works differently to loadPermissions You will need to use 2 lines

`
this.rolesService.addRole( SUPER_ADMIN : ['canViewDashboard', 'canAddOrganization', 'canViewOrganization', 'canEditOrganization'])
this.permissionService.loadPermission(['canViewDashboard', 'canAddOrganization', 'canViewOrganization', 'canEditOrganization'])`

this is what addRolesWithPermissions does

**Comment by AlexKhymenko** [comment]
https://github.com/AlexKhymenko/ngx-permissions/wiki/Managing-roles#confusion-with-roles

**Comment by nidhinkumar06** [comment]
> 

But if we have multiple roles then we should we
