### ISSUE TITLE
*ngxPermissionsOnly Or *ngxPermissionsExcept Not Working

### ISSUE THREAD

**Issue by MahmoudTarekAli** [AlexKhymenko/ngx-permissions#187]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

*ngxPermissionsOnly not working it says ("not Directive is matched on attribute ngxPermissionOnly") 

My Angular version is 12 I tried to install ngxpermission v8.1.1 this issue did not appear but another issue happen (ngxPermission does not have emod property and I think this issue is because of differences between versions I don't know 

## Environment

<pre><code>
Angular version: X.Y.Z
ngx-permissions version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
@MahmoudTarekAli Can You please share the code (if its possible can You create codePen). Did You import the NgxPermissionsModule? I have tested everything worked version 12 with 8.1.1

**Comment by MahmoudTarekAli** [comment]
yes i tried again with 8.1.1everything works fine... so should i use 8.1.1 with angular 12 not v13.0.1

**Comment by AlexKhymenko** [comment]
@MahmoudTarekAli use 8.1.1 with angular 12. Thank You will add to the documentation to help others.

**Comment by AlexKhymenko** [comment]
Updated. Thank You very much for helping!

**Comment by MahmoudTarekAli** [comment]
Thank you for your support and for this amazing library

**Comment by PhilippS93** [comment]
In Angular 13, also 8.1.1 is not working for me.
