### ISSUE TITLE
Component loaded twice

### ISSUE THREAD

**Issue by Lempkin** [AlexKhymenko/ngx-permissions#19]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

When I use lib to restrict access to a component, this component will be loaded twice if access is granted

## Expected behavior

The component should be loaded only once.

## Minimal reproduction of the problem with instructions

```
<div *ngxPermissionsOnly="['DEFINE_REPORTING']">
    <hsmt-reporting [siteId]="siteId"></hsmt-reporting>
</div>
```

With this code I can see that the hsmt-reporting component constructor is run twice if access is granted.

## Environment

<pre><code>
Angular version: 4.0.3
ngx-permissions version: 2.1.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Thank You. Will try to fix this week.

**Comment by AlexKhymenko** [comment]
Fixed in version 3.1.0

**Comment by Lempkin** [comment]
Now I got this error when I apply restrictions on divs : 

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'unsubscribe' of undefined
TypeError: Cannot read property 'unsubscribe' of undefined
    at NgxPermissionsDirective.webpackJsonp.../../../../ngx-permissions/ngx-permissions.umd.js.NgxPermissionsDirective.ngOnDestroy (vendor.bundle.js:19790)
    at callProviderLifecycles (vendor.bundle.js:101198)
    at callElementProvidersLifecycles (vendor.bundle.js:101167)
    at callLifecycleHooksChildrenFirst (vendor.bundle.js:101151)
    at destroyView (vendor.bundle.js:102373)
    at callViewAction (vendor.bundle.js:102484)
    at execComponentViewsAction (vendor.bundle.js:102426)
    at Object.destroyView (vendor.bundle.js:102372)
    at ViewContainerRef_.webpackJsonp.../../../core/@angular/core.es5.js.ViewContainerRef_.clear (vendor.bundle.js:100107)

**Comment by AlexKhymenko** [comment]
@Lempkin need more information tried applying to dive everything works. Created plunker would be nice.

**Comment by Lempkin** [comment]
Seems that problem is just with primeNg component 
```
<p-tabView class="hsmt-administration">
    <p-tabPanel [header]="siteConfig" *ngxPermissionsOnly="['ASSIGN_DEPT_SITE']">
...
```
If i refresh permissions the tab is supposed to appear/disappear, but it's not (I don't get the error above this time)

**Comment by AlexKhymenko** [comment]
:-) i dont use every library. Tried on simple component it works. If you want to get deeper you need to understand how p-tabPanel works.  How they generate template. For now can only recommend to use ng-template like this 

```
<p-tabView class="hsmt-administration">
   <ng-template [ngxPermissionsOnly]="['ASSIGN_DEPT_SITE']">
          <p-tabPanel [header]="siteConfig">

```

**Comment by Lempkin** [comment]
@AlexKhymenko it happen also with ngxPermissionsExcept
