### ISSUE TITLE
Can't install nix-permissions latest, but can install 8.1.1

### ISSUE THREAD

**Issue by RichardBoyder** [AlexKhymenko/ngx-permissions#194]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

When installing 13.0.0 or 13.1.0 getting a install error:
richardboyder@Richards-MBP-3 Titanic % npm i ngx-permissions@13.0.0
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: titanic@0.0.0
npm ERR! Found: @angular/core@12.2.16
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"~12.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@">=13 || >16" from ngx-permissions@13.0.0
npm ERR! node_modules/ngx-permissions
npm ERR!   ngx-permissions@"13.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/richardboyder/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richardboyder/.npm/_logs/2022-02-23T10_46_38_467Z-debug.log

## Expected behavior

Expect the latest package to be able to install. 
We do have angular ~12.2.0 installed..  with angular core ~12.2.0.

## Environment

<pre><code>
Angular version: ~12.2.0
ngx-permissions version: 13.0.0

I have tested... 8.1.1 installs no problem... but as per the above error... latest doesn't.

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Hi @RichardBoyder . Version 13 is for angular 13, please use 8.1.1 for angular 12. Have a great day.
