### ISSUE TITLE
Unauthorized Strategies

### ISSUE THREAD

**Issue by AntonLebiodkin** [AlexKhymenko/ngx-permissions#20]
Hi, Alex! We are happy to use your library in our project!

Could you help me please with one question? 
I need to disable the button when the user hasn't required permissions and now the only possibility to achieve this, as I understood, is to clone template of the button, make it disabled and pass it to `elseBlock`.

Is it possible to avoid such of code cloning and provide kind of predefined Strategies of actions to elements with which user has no rights to interact?

Thank you for your attention!

**Comment by AlexKhymenko** [comment]
This will required me to create directive that works on css. This required normal amount of time unfortunately i dont have time right now. When i will have i will create directive that works on css and not removes object from the dom.

**Comment by AlexKhymenko** [comment]
Fixed in version 4.1 initial documentation https://github.com/AlexKhymenko/ngx-permissions/wiki/Controlling-access-in-views#custom-behaviour
