### ISSUE TITLE
`getPermission` returns an incomplete type

### ISSUE THREAD

**Issue by framasev** [AlexKhymenko/ngx-permissions#202]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[✓] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>
## Current behavior

`getPermission` method return type is `NgxPermission`.

## Expected behavior

`getPermission` method return type is `NgxPermission | undefined`;

**Comment by AlexKhymenko** [comment]
@framasev Thank You it makes sense. Will fix when possible

**Comment by AlexKhymenko** [comment]
Fixed on the latest release by the great person @jkubiszewski
