### ISSUE TITLE
Can't access component variables

### ISSUE THREAD

**Issue by AntonLebiodkin** [AlexKhymenko/ngx-permissions#21]
Hello guys!
I have kind of problem, when I can't access to component class fields from my `ng-template`'s.
Could you help me, how could i solve this problem?

Here is code example
```
<ng-template [ngxPermissionsOnly]="'PERMISSION'"
             [ngxPermissionsOnlyThen]="allowAccess"
             [ngxPermissionsOnlyElse]="denyAccess">
</ng-template>`


<ng-template #allowAccess>
    <button type="submit" class="btn btn-primary">{{ componentVar }}</button>
</ng-template>

<ng-template #denyAccess>
    <button disabled type="submit" class="btn btn-primary">{{ componentVar }}</button>
</ng-template>
```

And text where should be componentVar is empty

**Comment by AlexKhymenko** [comment]
Hi. You can do something like this.


`<ng-template [ngxPermissionsOnly]="'PERMISSION'"
             [ngxPermissionsOnlyThen]="allowAccess"
             [ngxPermissionsOnlyElse]="denyAccess">
</ng-template>`


<ng-template #allowAccess let-variable="componentVar">
    <button type="submit" class="btn btn-primary">{{ variable }}</button>
</ng-template>

<ng-template #denyAccess let-variable="componentVar">
    <button disabled type="submit" class="btn btn-primary">{{ variable }}</button>
</ng-template>`
