### ISSUE TITLE
ngx-permissions not working in child-components (features)

### ISSUE THREAD

**Issue by atarazavi** [AlexKhymenko/ngx-permissions#210]
When a child component with this html code:
![image](https://user-images.githubusercontent.com/32979933/205017710-c68f9703-fd02-409d-81ba-b9f34e3d1b3e.png)

is being loaded, this error happens:

![image](https://user-images.githubusercontent.com/32979933/205006704-bfaf7739-2015-4b45-b5f0-9c37d02bea55.png)

Importing NgxPermissionsModule.forRoot() in app.module is done!
Importing NgxPermissionsModule.forChild(), in child components is done!
Whether it's LazyLoading or not, it doesn't work for the components! 
BUT
when I add ***ngxPermissionsOnly="['ADMIN']"** to app.component.html it works! So It's facing the problem just for child components!
I tried many different ways and found a solution! Including the child components in **declarations** array in app.module!
But I don't like this solution! And I think it is in contrast with the LazyLoading concept!
Also using sharedModule didn't solve the problem!

## Environment
Angular version: 14.2.X
ngx-permissions version: 14.0.0

Browser:
- [ ] Chrome (desktop) version 107.0.5304.123 (Official Build) (64-bit)

**Comment by senbagaraman04** [comment]
I work with **`angular 13.x`** and **`ngx-permission 13.x`** - it works by importing` forchild()` in the **lazy loaded module**. Can you share the minimal reproducible code in stack-blitz?
