### ISSUE TITLE
[feaure] - NgxPermissionsGuard -  implement "canMatch"

### ISSUE THREAD

**Issue by joelghill** [AlexKhymenko/ngx-permissions#216]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
</code></pre>

Angular has a new route guard introduced in Angular 14 called [canMatch](https://angular.io/api/router/CanMatch) that is likely going to replace  `canLoad`.  It would be great of the `ngx-permissions` library had this implemented since it looks like an incredibly useful guard.

<pre><code>
Angular version: 15.2.0
ngx-permissions version: 14.0.0

**Comment by AlexKhymenko** [comment]
@joelghill  This feature will be implemented. Just need some free time

**Comment by AlexKhymenko** [comment]
Available in new release 14.1.0
