### ISSUE TITLE
   routeStateSnapshot in redirect is undefined

### ISSUE THREAD

**Issue by InbarTakdim** [AlexKhymenko/ngx-permissions#219]
what can be the reason of  routeStateSnapshot is undefined it the funstion of redirect?
 permissions: {
            only: [Roles.LOCATION_ENERGY, Roles.LOCATION_MAP],
            redirectTo: {
              LOCATION_ENERGY: (
                rejectedPermissionName: string,
                activateRouteSnapshot: ActivatedRouteSnapshot,
                routeStateSnapshot: RouterStateSnapshot
              ): string => {
                return `${routeStateSnapshot?.url}/1`;
              },
              LOCATION_MAP: (
                rejectedPermissionName: string,
                activateRouteSnapshot: ActivatedRouteSnapshot,
                routeStateSnapshot: RouterStateSnapshot
              ): string => {
                return `${routeStateSnapshot?.url}/2`;
              }
            }
          }

**Comment by AlexKhymenko** [comment]
I'm sorry ite better to ask on stackoverflow or chatGpt. The problem is with overrall solution not with library
