### ISSUE TITLE
TestModule

### ISSUE THREAD

**Issue by davidkarlsen** [AlexKhymenko/ngx-permissions#22]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
No test support. 

## Expected behavior
It would be nice with mock module or the likes, so that:
* the directives would be valid (and hence the test can be setup)
* a mock permission evaluation, which would always allow access 

## Environment

<pre><code>
Angular version: 5.2.1
ngx-permissions version: 3.1.0

Browser:
All

**Comment by AlexKhymenko** [comment]
I will investigate into this issue. But i can't give any estimates.

**Comment by yogiswar1987** [comment]
I would like to see this implemented as well

**Comment by AlexKhymenko** [comment]
@davidkarlsen @yogiswar1987 Do You think you need the whole module stubbed or only directive for now.

**Comment by davidkarlsen** [comment]
Could maybe start with directive? And if needed expand?

**Comment by AlexKhymenko** [comment]
@davidkarlsen I guess yes will create 2 directives one for success and one for not success :-) Will see if it will be enough

**Comment by AlexKhymenko** [comment]
@davidkarlsen i have implemented it but i have one problem. When testing in the library everything is ok. When im using angular cli with library from node_modules have error. 

`Unexpected value 'NgxPermissionsAllowStubDirective' declared by the module 'DynamicTestModule'. Please add a @Pipe/@Directive/@Component annotation.`

Will try to figure it out this week.

**Comment by AlexKhymenko** [comment]
Added in 3.2.0. initial documentation > https://github.com/AlexKhymenko/ngx-permissions/wiki/Testing.

**Comment by davidkarlsen** [comment]
Awesome - thanks a lot!
