### ISSUE TITLE
Set NgxPermissionsGuard functions to protected access levels

### ISSUE THREAD

**Issue by joelghill** [AlexKhymenko/ngx-permissions#220]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
I'm trying to extend the behavior of the `NgxPermissionsGuard` in a project to fit a custom use case. I'd like to be able to create a new class that extends `NgxPermissionsGuard`  and overwrite some of the methods to better meet my needs.

## Expected behavior
I would expect that some, if not all,  of the private internal methods used by NgxPermissionsGuard would be marked as protected. This would allow certain behaviors to be overwritten or extended by people consuming the library.

## Environment

<pre><code>
Angular version: 15.1
ngx-permissions version: 15.0

**Comment by AlexKhymenko** [comment]
@joelghill available in 15.0.1

**Comment by joelghill** [comment]
Thank you!
