### ISSUE TITLE
Unable to make NgxPermissionsService singleton across application and dependent libraries

### ISSUE THREAD

**Issue by mrgopalakrishnan** [AlexKhymenko/ngx-permissions#222]
I'm trying to use NgxPermissionsService as singleton acroo main app and some libraries. the permissions will be loaded by one library and other libraries and main app has to use the same permissions loaded.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior
Unable to make the service singleton and there is no documentation to explain this scenario.

## Expected behavior
Update in the documentation to explain how to share the service and directives across app and libraries

## Minimal reproduction of the problem with instructions
<pre>Lib Module </pre>
<code>@NgModule({
  declarations: [
  ],
  imports: [
    HttpClientModule,
    NgxPermissionsModule
  ]
})
export class MyLibModule{}</code

<pre>Main app module</pre>
<code>
 NgxPermissionsModule.forRoot(),
    MyLibModule.forRoot(),
 </code>
 

## Environment

<pre><code>
Angular version: 15.2.4
ngx-permissions version: 14.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version XX

**Comment by AlexKhymenko** [comment]
@mrgopalakrishnan Sorry can't reproduce

**Comment by mrgopalakrishnan** [comment]
The issue is with the deep dependencies of the services. solved by providing all dependencies in shared
