### ISSUE TITLE
Angular 16 support with providers

### ISSUE THREAD

**Issue by constantinosergiou** [AlexKhymenko/ngx-permissions#225]
is it possible to update to angular 16?

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z
ngx-permissions version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Hi @constantinosergiou I need to investigate how to do it right. If You can do faster please create PR. Thank You

**Comment by DarkoGjakovski** [comment]
Any updates here? :)

**Comment by Mahmoudibrahim03** [comment]
I think it's updated you can check now @constantinosergiou

**Comment by AlexKhymenko** [comment]
Updated to angular 16 by nice guy for created pr
