### ISSUE TITLE
How to use Rolle and Permission without Rolle

### ISSUE THREAD

**Issue by elvispdosreis** [AlexKhymenko/ngx-permissions#228]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
</code></pre>

## Expected behavior
I have doubts about how to work with roles and permissions.
For example, I have some Roles ['Super Admin', 'Admin', 'User', 'Guest'], but these roles are standard and do not have any permissions within them, but I have some separate permissions that are not linked to any roles.
how do i add these check rules in the html ngxPermissionsOnly

## Environment

<pre><code>
Angular version: 15.2.3
ngx-permissions version: 15.0.1

Browser:
- [X] Chrome (desktop) version 115.057
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
@elvispdosreis In Your case they are all permissions just concatenate 2 arrays and insert into loadPermissions function. Hope this helps.

**Comment by AlexKhymenko** [comment]
the library is based on permissions. So basically when you write ngxPermissionsOnly=['createUser'] it will check if user has permission createUser.
