### ISSUE TITLE
3.2.0  is not including new NgxPermissionsAllowStubDirective, NgxPermissionsRestrictStubDirective with NgxPermissionsModule.

### ISSUE THREAD

**Issue by leoclc** [AlexKhymenko/ngx-permissions#23]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Version 3.2.0 is not including new NgxPermissionsAllowStubDirective, NgxPermissionsRestrictStubDirective with the NgxPermissionsModule.

## Expected behavior

I am sure you just forgot to add this?

## Environment

<pre><code>

Browser:
- [X] Chrome (desktop) version XX
- [X] Chrome (Android) version XX
- [X] Chrome (iOS) version XX
- [X] Firefox version XX
- [X] Safari (desktop) version XX
- [X] Safari (iOS) version XX
- [X] IE version XX
- [X ] Edge version XX

**Comment by AlexKhymenko** [comment]
Its not in module. Its outside specifically for testing. 
You can import like this
`import { NgxPermissionsAllowStubDirective} from 'ngx-permissions';
`

**Comment by AlexKhymenko** [comment]
Ok tried to compile with aot and prod build and found present in the form of this issue https://github.com/angular/angular/issues/13590. Will try to figure something out but i don't want this files to be in the build the are for testing purposes.

**Comment by AlexKhymenko** [comment]
Fixed in version 3.2.1
