### ISSUE TITLE
Identify the directive in the loadPermissions function

### ISSUE THREAD

**Issue by wfpaisa** [AlexKhymenko/ngx-permissions#230]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

be able to identify the type of directive to be able to make an Only or an except

## Expected behavior
```html
<div
  ... *ngxPermissionsOnly="['PCO_SADM']"
  ... *ngxPermissionsExcept="['PCO_SADM']"
>
```

```js
this.permissions.loadPermissions(roles, (permissionName, permissionStore, permissionType <----) => {

     ----> console.log('-- permissionType:', permissionType);

      if(permissionType === '~only') return ...
      if(permissionType === '~exept') return...

      return !!permissionStore[permissionName as string];
});
```

**Comment by AlexKhymenko** [comment]
@wfpaisa Can You please create pr for this feature?
