### ISSUE TITLE
NgxPermissionsGuard deprecated

### ISSUE THREAD

**Issue by lufo88ita** [AlexKhymenko/ngx-permissions#231]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior
NgxPermissionsGuard is deprecated in the latest version of the library ( 16.0.1 )

## Expected behavior

NgxPermissionsGuard not deprecated or a substitute must be available

## Minimal reproduction of the problem with instructions
Just use NgxPermissionsGuard in a project with angular 16

## Environment

Angular version: 16.2.12
ngx-permissions version: 16.0.1

**Comment by AlexKhymenko** [comment]
Hi @lufo88ita use ngxPermissionsGuard. Its a functional guard.

**Comment by lufo88ita** [comment]
Many thanks. :-) I closed the issue
