### ISSUE TITLE
Angular 17 Support

### ISSUE THREAD

**Issue by ARTWINPRO** [AlexKhymenko/ngx-permissions#232]
## When will be able support for angular 17?

<pre><code>
[+] Feature request 
</code></pre>
 
## Environment

<pre><code>
Angular version: 17.0.3
ngx-permissions version: 16

**Comment by Hiaslafson** [comment]
Any updates?

**Comment by S0543830** [comment]
Any updates?

**Comment by AlexKhymenko** [comment]
@Thanks for waiting new version is released.
