### ISSUE TITLE
Angular 18 Support

### ISSUE THREAD

**Issue by davidsarkany** [AlexKhymenko/ngx-permissions#236]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>Angular version: 18.0.6
ngx-permissions version: 17.1.0
</code></pre>

**Comment by AlexKhymenko** [comment]
Hi ngx permissions are working with angular 18 perfectly.
