### ISSUE TITLE
Angular 18 Support

### ISSUE THREAD

**Issue by rms2219** [AlexKhymenko/ngx-permissions#239]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x] Feature request
[ ] Documentation issue or request
</code></pre>

## Expected behavior
Please add support for Angular 18.

**Comment by AlexKhymenko** [comment]
@rms2219 Hi. Do You have any problems with angular 18, cause library supports 18, and 19 and so on.

**Comment by rms2219** [comment]
I haven't attempted yet. I assumed (apparently incorrectly) that there was no support yet, as there's a library release associated with every other major version of Angular. I'm preparing to upgrade my application from 17 to 18, and am going through the process of ensuring all of my dependencies will support the update.

**Comment by AlexKhymenko** [comment]
@rms2219 I'm using it with angular 18, no problems. There is no need for 18 release cause there are no changes, and everything works. Happy upgrade for You :-)
