### ISSUE TITLE
Usage of roles

### ISSUE THREAD

**Issue by onatschirmaj** [AlexKhymenko/ngx-permissions#24]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Neither the directives `ngxPermissionsOnly`, `ngxPermissionsExcept`, nor `except` and `only` with routes work when using roles. Neither the plunker demo is working with roles.

## Expected behavior

When user adds roles using their service, from the documentation it seems, they should be appliable as well as permissions added using their service.

## Minimal reproduction of the problem with instructions

Go to roles page
https://plnkr.co/edit/n6Wa6hXg0JzI6e050wBt?p=preview

## Environment

<pre><code>
Angular version: v5.2.1
ngx-permissions version: X.Y.Z

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Need to update the docs and plunker. Will try to do it asap

**Comment by AlexKhymenko** [comment]
@onatschirmaj Updated the documentation and plunker. Is the new version understandable?

**Comment by onatschirmaj** [comment]
@AlexKhymenko so that the permissions contained in role have to be added first, right? I understand that from the plunker, but to be honest, I can`t see it in the doccumentation. Thanks a lot anyway for updating the plunker.

**Comment by AlexKhymenko** [comment]
@onatschirmaj in comments here :-) 
https://github.com/AlexKhymenko/ngx-permissions/wiki/Managing-roles#defining-roles

**Comment by onatschirmaj** [comment]
My bad, I was reading README :-[ Thanks a lot
