### ISSUE TITLE
ngxPermissionsOnly not working in template

### ISSUE THREAD

**Issue by gauravhanda25** [AlexKhymenko/ngx-permissions#27]
## How I used -

`<p ngxPermissionsOnly="GUEST">Members online</p>`

## Permissions set in component and added role as below - 

`   NgxPermissionsService.loadPermissions(["A"]);
    NgxRolesService.addRole('ADMIN', ['A']	);`

## Code added in component to check role is added in permission or not - 

`let roles = NgxRolesService.getRoles();`
`NgxRolesService.roles$.subscribe((data) => {
	    console.log(data);
	})`

### console.log returns below - 

`{
  "ADMIN": {
    "name": "ADMIN",
    "validationFunction": [
      "A"
    ]
  }
}`

### Tried following possibilities - 
`<p ngxPermissionsOnly="'GUEST'">Members online</p>`
`<p ngxPermissionsOnly="'[GUEST']">Members online</p>`

but still GUEST permission's p tag is visible or even directive not readable in template.

**Comment by AlexKhymenko** [comment]
try with * `<p *ngxPermissionsOnly="'[GUEST']">Members online</p>`

**Comment by gauravhanda25** [comment]
It gives me error of can't binding. This syntax does not work in my application. Anything else I can provide about my application ?

**Comment by gauravhanda25** [comment]
Tried this also from plunker demo 
`*ngxPermissionsOnly="'GUEST'"`

but didnt work below is the error - 
` <p [ERROR ->]*ngxPermissionsOnly="'[GUEST']">Members online</p>`

**Comment by AlexKhymenko** [comment]
"'[GUEST']" should be "'['GUEST']"

**Comment by gauravhanda25** [comment]
ERROR Error: Uncaught (in promise): Error: Template parse errors: Can't bind to 'ngxPermissionsOnly' since it isn't a known property of 'p'. ("
          </div>
          `<p [ERROR ->]*ngxPermissionsOnly="['GUEST']">Members online</p>`

**Comment by AlexKhymenko** [comment]
Please read the documentation https://github.com/AlexKhymenko/ngx-permissions/wiki
