### ISSUE TITLE
loadPermissions not removing old permissions

### ISSUE THREAD

**Issue by dsgriffin** [AlexKhymenko/ngx-permissions#28]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

In the [Multiple Permissions](https://github.com/AlexKhymenko/ngx-permissions#multiple-permissions) section of the docs it states that `loadPermissions` "will remove older permissions and pass only new"

## Expected behavior

`loadPermissions` should remove older permissions and replace with the new

## Minimal reproduction of the problem with instructions

``` 
this.ngxPermissionsService.loadPermissions(['admin', 'test']);
this.ngxPermissionsService.loadPermissions(['another', 'random']);
// 'admin' and 'test' permissions still exist
```

**Comment by AlexKhymenko** [comment]
Fixed in version 3.2.2
