### ISSUE TITLE
Always check by lower level of role

### ISSUE THREAD

**Issue by eduardogdo** [AlexKhymenko/ngx-permissions#3]
Hi, i extend my congratulations for this component. But when i have a user with role admin and role editor and want to access a functionality with role admin the user cant not access because it have a role with lower permission. thanks again

**Comment by AlexKhymenko** [comment]
Hi Eduard. Can you please show in code or give more clarification so i can fix this issue faster. Thank You it will help me a lot.

**Comment by eduardogdo** [comment]
Sorry Alex i work out a little more and it working was my mistake. Thanks again for the faster response and congratulations for this great component

**Comment by AlexKhymenko** [comment]
Thank You have a Great Day!!
