### ISSUE TITLE
Override NgxGuardPermissions

### ISSUE THREAD

**Issue by panay** [AlexKhymenko/ngx-permissions#30]
Hello, everyone!

I would like to know could I override the NgxGuardPermissions? I just want to make logout if permission is denied.

Thanks!

**Comment by AlexKhymenko** [comment]
You probably should use different approach, Depending how you make request. but if it usual way just use interceptor  and if you have 401 error redirect to login.

**Comment by panay** [comment]
Thank you for the answer!
I create another guard that placed near to NgxPermissionGuard and who has this code:
`@Injectable()
export class PermissionsAuthGuard implements CanLoad {
  constructor(private store: Store<AuthStore.IState>,
              private router: Router,
              private permissionsGuard: NgxPermissionsGuard) {
  }

  canLoad(route: Route) {

    const loaded = this.permissionsGuard.canLoad(route);

    (<Promise<boolean>>loaded).then(load => {
      if (!load) {
        this.store.dispatch(new AuthStoreActions.Logout({}));
        return false;
      }
      return true;
    }).catch(() => {
      return false;
    });

    return true;
  }
}`

Probably this code will help to solve the same problem for anyone else.

**Comment by connectchurch** [comment]
How can extends this guards in Angular 9? Keep using promises? or now, Observable?
