### ISSUE TITLE
Observable.merge AOT compilation

### ISSUE THREAD

**Issue by zverbeta** [AlexKhymenko/ngx-permissions#31]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

If i compile project with aot (--prod) flag. I got error in browser console `Observable.merge is not a function` in `validateExceptOnlyPermissions` 

## Environment

<pre><code>
Angular version: 5.2.0
ngx-permissions version: 3.2.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Check different ngrx versions. Try 5.5.2

**Comment by zverbeta** [comment]
But i have rxjs 5.5.2

**Comment by AlexKhymenko** [comment]
This is bug angular cli + rxjs somehow it removes the merge operator.

**Comment by AlexKhymenko** [comment]
After having too much pain with Observable.merge changed it to operator merge. Can You please try again.

**Comment by zverbeta** [comment]
I installed 3.2.4 version and it's working. Thanks

**Comment by zverbeta** [comment]
Sorry, I tested without the prod flag, the bug still exists

**Comment by AlexKhymenko** [comment]
Fixed in version 4.0.0. Now minimal rxjs version is 5.5.
