### ISSUE TITLE
Get permissions after page refresh

### ISSUE THREAD

**Issue by deyvidfk** [AlexKhymenko/ngx-permissions#35]
I do not know if I forgot something, but by forcing the reload of the page, I lose the permissions in memory.
The solution to my problem was to get the permissions saved in the localStorage and after the reload call the loadPermissions([permissions]) method ;
Would that be the best approach?

**Comment by AlexKhymenko** [comment]
Yep. This is the most common approach https://github.com/AlexKhymenko/ngx-permissions/wiki/common-use-cases
