### ISSUE TITLE
Is there any possibility for strict roles with shared permission?

### ISSUE THREAD

**Issue by sbabich-nix** [AlexKhymenko/ngx-permissions#36]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior

Validation passes if permission is common for different roles
## Expected behavior

Need to have strict permission set validation.

ROLE_A: ['perm_a', 'perm_b']
ROLE_B: ['perm_a]

Need to show element only to ROLE_A and completely hide to ROLE_B.

## Environment

<pre><code>
Angular version: 5.1.0
ngx-permissions version: 4.1.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
I'm Sorry i dont fully understand your problem.

Maybe what you are trying to achieve is 
```

 <ng-template [ngxPermissionsOnly]="'ROLE_A'"  [ngxPermissionsExcept]="'ROLE_B'">
    <div>You can see this text congrats</div>
 </ng-template>
```

**Comment by AlexKhymenko** [comment]
I'm sorry but i dont understand what you want. If you need to write something custom use function.

**Comment by sbabich-nix** [comment]
```js
// app.module
this.role$.addRoles({
    'ADMIN': ['users', 'admins'],
    'USER': ['users']
});
```

```js
// view.component
this.perm$.addPermission(['users', 'admins']);
```

```html
<!--view.component.html-->
<ng-template [ngxPermissionsOnly]="'ADMIN'" [ngxPermissionsExcept]="'USER'">
  <p>ADMIN</p>
</ng-template>
<ng-template [ngxPermissionsOnly]="'USER'" [ngxPermissionsExcept]="'ADMIN'">
  <p>USER</p>
</ng-template>
```

I suppose that in this particular case `<p>ADMIN</p>` should be visible, but none is visible.

**Comment by AlexKhymenko** [comment]
Roles are checking permissions. And is this case you specify that user has 'users' and 'admins' permissions. So both roles are valid. What is written here in [ngxPermissionsExcept]="'USER'"
is it should not have 'users' permissions. [ngxPermissionsOnly]="'ADMIN'" = it should have 'users' and 'admins' permission. But first will always fail cause it have users permissions. Probably what you want is this 

```
this.role$.addRoles({
    'ADMIN': ['admins'],
    'USER': ['users']
});
```

**Comment by sbabich-nix** [comment]
Actually in my case I need to separate permissions and roles to operate. Some parts should be restricted by permissions which is working well, but some parts are restricted by **roles**, and roles can overlap with permissions.

Is it possible to suggest adding a directive like `ngxRolesOnly`?

**Comment by AlexKhymenko** [comment]
Mostly roles are just containers for the permissions. The main goal of roles is they use 'and' operator on permissions. So you dont need to write your custom permission like this

```
 this.permissionsService.addPermission('admin', (permissionName, permissionsObject) => {
        return !!permissionsObject['admin'] &&  !!permissionsObject['users'];
    });
```

you just write 

```
this.role$.addRoles({
    'ADMIN': ['users', 'admins']
});

```

For your case you can write like this 

```
 this.permissionsService.addPermission('user', (permissionName, permissionsObject) => {
        return !permissionsObject['admin'] &&  !!permissionsObject['users'];
    });
```

**Comment by davidbaroncp** [comment]
I aggree with @sbabich-nix, we should have the **ngxRolesOnly** & **ngxRolesExcept** directives, imagine the case of a role having many permissions (_ROLE_NAME: ['PERMISSION_A, PERMISSION_B, ..., PERMISSION_Z']_).
If you want to hide a certain feature for all the permissions of that role, it would be shorter to write this:
```
<div *ngxRolesExcept="['ROLE_NAME']">
  The FEATURE to hide
</div>
```
Instead of this:
```
<div *ngxPermissionsExcept="['PERMISSION_A, PERMISSION_B, ..., PERMISSION_Z']">
  The FEATURE to hide
</div>
```

**Comment by AlexKhymenko** [comment]
@davidbaroncp but its working right now like this.

**Comment by davidbaroncp** [comment]
@AlexKhymenko Are you meaning that you can provide a role name to **ngxPermissionsExcept** ?
Because I tried and it did not work for me... :cry:

**Comment by AlexKhymenko** [comment]
@davidbaroncp i have rechecked its working https://plnkr.co/edit/F3kPRhmCudKVwQdoZr8r?p=preview go to roles page you will see it shows message except guest then i add guest role it dissapears

**Comment by davidbaroncp** [comment]
@AlexKhymenko Thank you for your answers, I will check that.

**Comment by AlexKhymenko** [comment]
@sbabich-nix after thinking why not just use it like this The user will not see it cause he has't got 2 permissions


```
<ng-template [ngxPermissionsOnly]="'ADMIN'">
  <p>ADMIN</p>
</ng-template>

```

**Comment by AlexKhymenko** [comment]
@sbabich-nix I will close this issue. For now directive checks roles and permissions at the same time.
