### ISSUE TITLE
redirectTo with query parameters

### ISSUE THREAD

**Issue by stoto34** [AlexKhymenko/ngx-permissions#37]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior

It's not an issue, just a question : I would like to know how can I redirect on page with the redirectTo command into a routing.

## Expected behavior

```
{
			path: 'test/:id',
			component: testComponent,
			canActivate: [NgxPermissionsGuard],
			data: {
				permissions: {
					only: ["ROLE_USER"],
					redirectTo: ['/login'] // would like to redirect to /login?not_authorized=1 
				}
			}
		},
```

## Environment

<pre><code>
Angular version: 5.3.2
ngx-permissions version: 4.1.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Under the hood it using 'navigate command' this should work

```
redirectTo: {
            navigationCommands: ['/login'],
            navigationExtras: {
                not_authorized: 1
            }
        }   
```
Documentation here https://github.com/AlexKhymenko/ngx-permissions/wiki/Usage-with-routes#property-redirectto

**Comment by AlexKhymenko** [comment]
```
redirectTo: {
            navigationCommands: ['/login'],
            navigationExtras: {
                      queryParams: {   'not_authorized': 1 },          
            }
        }       
```

try this one

**Comment by stoto34** [comment]
Great ! It works ! :)
I think I will have some more question about your great package
