### ISSUE TITLE
How to listen permissionsAuthorized event

### ISSUE THREAD

**Issue by yunier0525** [AlexKhymenko/ngx-permissions#38]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior

I'm trying to capture the permissionsAuthorized event that is thrown when the permission is granted, but the method that I have linked to the event is not executed.

## Expected behavior

I need to listen when permission is granted.

## Minimal reproduction of the problem with instructions

Template side:
`<li *ngxPermissionsOnly="'canAccessSettings'" (permissionsAuthorized)="reloadMenu()">Item<li>`

Component side:
`
public reloadMenu($event): void {
        console.log('reloadMenu', $event);
}
`

## Environment

<pre><code>
Angular version: 5.2.5
ngx-permissions version: 4.1.0

Browser:
- [X] Chrome (desktop) version 64.0.3282.186
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
I have tested unfortunately its not working with * form its working with ng template form. Not my restriction :-)
This one should work.

`<ng-template [ngxPermissionsOnly]="'ADMIN'" (permissionsUnauthorized)="reloadMenu()" `
