### ISSUE TITLE
User has permission to current route

### ISSUE THREAD

**Issue by dwayneforehand** [AlexKhymenko/ngx-permissions#39]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior

First thank you for this!  It was just what we were looking for.  We have functionality where a user can impersonate another role.  I’m wondering how I’d go about checking to see if if the user has permission to the current route?

## Environment

<pre><code>
Angular version: X.Y.Z
ngx-permissions version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Hi. There is the whole section regarding this issue :-)

https://github.com/AlexKhymenko/ngx-permissions/wiki/Usage-with-routes

**Comment by AlexKhymenko** [comment]
If you mean that it can change while user is on the page.  You can listen to permissions and when they change rerun guard and resolvers.
