### ISSUE TITLE
*ngFor

### ISSUE THREAD

**Issue by guygit** [AlexKhymenko/ngx-permissions#4]
Hi,

it seems, the directives (eg. ngxPermissionsOnly) cannot be used within an "*ngFor" loop.

Example: 
...*ngFor="let child of children" ..
<td yourDirective>{{child.value}}

In the example above, {{child.value}} does not get rendered - it seems to be shadowed by your Directive.

Can you confirm? 
Is it by intent?

Thx a lot,

raven

**Comment by AlexKhymenko** [comment]
Hi it depends on you intention. But the main restriction it **can't** be used in the same line as *ngFor(**Angular restriction not the library like you can't use ngIf with ngFor**)
```
 <div *ngFor="let elem of elements" *ngxPermissionsOnly="Guest">
     this will not work
  </div>
 </div>
```

and if you have permissions in children you can use it like this

```
<div *ngFor="let item of group.children">
        <ng-container *ngxPermissionsOnly="item.permission">
          <a
             [routerLink]="[item.url]"
             (click)="toggleOpen()"
             routerLinkActive="active"
             [ngClass]="{'active': item.isActive}"
             class="menu-item">
            <span translate>{{item.title}}</span>
          </a>
        </ng-container>
      </div>
``` 
and the 3 when you dont what to show ngFor at all You write like this 

```
      <ng-container *ngxPermissionsOnly="Admin">
         <div *ngFor="let item of group.children" ngClass="{'separator': item.separator}" >
         </div> 
      <ng-container>
```

Hope This helps. Have A Nice Day!!
