### ISSUE TITLE
How can use "canDoSomething" permission without role into the view ?

### ISSUE THREAD

**Issue by stoto34** [AlexKhymenko/ngx-permissions#40]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior

I'm not sure if I understood well but how can I use my permissions into the view ? I've got this permission : "canEdit" and I would like  to do something like that and I don't know if it's possible : 

`<ng-template [ngxPermissionsOnly]="['ROLE_USER']" OR "canEdit">
    <button fxHide.xs="true" fxShow.gt-sm="true" mat-raised-button color="primary" (click)="redirect('items/add')"><i class="material-icons">add</i>Add item</button>
</ng-template>`

Is it possible to use the permission and not the role ?

Thank you :)

## Environment

<pre><code>
Angular version: X.Y.Z
ngx-permissions version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Yes its possible the directive takes roles and permissions.

 [ngxPermissionsOnly]="['ROLE_USER', 'YOUR_PERMISSION']"

**Comment by stoto34** [comment]
Great, I gonna test that :)

Thank you again !
