### ISSUE TITLE
Support for loading the role / permission during the route guard check

### ISSUE THREAD

**Issue by bjornharvold** [AlexKhymenko/ngx-permissions#41]
- make sure you have the correct permission
- go to a url with permission guard on it using that permission
- refresh the page
==> In my use case, there is no way I can load the permission fast enough because I cannot load the permission at application start. I need a way to be able to check permission with the server using the permission guard.
 
## I'm submitting a...
<pre><code>
[X ] Feature request
</code></pre>

## Current behavior
Not currently possible

## Environment

<pre><code>
Angular CLI: 1.7.4
Node: 9.11.1
OS: darwin x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
ngx-permissions version: 4.1.0

**Comment by AlexKhymenko** [comment]
Hi. Sorry had a little rest. Do  You need still help ?. You can define permission as a function that will check permissions.

**Comment by bjornharvold** [comment]
Hi @AlexKhymenko! 

Can you point me to some code that shows the NgxPermissionsGuard doing that? 

Thank you :-)

**Comment by AlexKhymenko** [comment]
Here checkPermissionsService is service that will check permissions on backend it should return promise
```
this.permissionsService.addPermission('permissions', (permissionName, permissionsObject) => {
       return this.checkPermissionsService().toPromise();
     });
```

**Comment by AlexKhymenko** [comment]
@bjornharvold Do you still have problems ?

**Comment by bjornharvold** [comment]
Hi @AlexKhymenko. I didn't receive a notification from Github on your post 4 days ago. Looking at it now. This looks doable :-) Closing ticket when I get it to work.
