### ISSUE TITLE
Please release v6 as rxjs 6 has been released and it is not compatible with current version

### ISSUE THREAD

**Issue by zorrme** [AlexKhymenko/ngx-permissions#43]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Does not work with rxjs 6.0

## Environment

<pre><code>
Angular version: X.Y.Z
ngx-permissions version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Hi there is pull request created by @thekiba  . But i can check it only on Saturday or Sunday. But for sure if everything is ok new version will be released before Monday.

**Comment by thekiba** [comment]
@AlexKhymenko We already use this on production. You may publish as beta version. What you think?

**Comment by AlexKhymenko** [comment]
@thekiba I would be glad to publish. I'm just far away from computer right now :-)

**Comment by AlexKhymenko** [comment]
Released version 5.0.0-rc.0

**Comment by AlexKhymenko** [comment]
For now dont use new version due to https://github.com/AlexKhymenko/ngx-permissions/issues/45

**Comment by AlexKhymenko** [comment]
nevermind all good :-)
