### ISSUE TITLE
Move plunker to statblitz

### ISSUE THREAD

**Issue by AlexKhymenko** [AlexKhymenko/ngx-permissions#46]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z
ngx-permissions version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by jfcere** [comment]
This can be a start if you want : https://stackblitz.com/edit/ngx-permissions-onpush 😄
