### ISSUE TITLE
Permissions doesn't persist

### ISSUE THREAD

**Issue by chaosLegacy** [AlexKhymenko/ngx-permissions#51]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Hi,Thank you all for your great job, I'm using this library for a web application that support multiple roles each role has different permissions my problem is that the permissions that i load doesn't persist in the browser a soon as i refresh the page the getPermissions function return  an empty object
PS: I'm using ngx-permissions 4.0.0 instead of 5.0.0 because i get this error rxjs.merge is not a function
## Expected behavior

The permissions should persist even when we change the navigation 

## Environment

<pre><code>
Angular version: 5.1.0
ngx-permissions version: 4.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Hi version 5 is for rxjs version 6.
For the issue https://github.com/AlexKhymenko/ngx-permissions/wiki/common-use-cases#save-permissions-on-page-refresh

**Comment by AlexKhymenko** [comment]
There are some ways to do it createSpecialPermission and in function specify what you want.
Another way is extract common permission to array and pass the array with other permissions

**Comment by AlexKhymenko** [comment]
@chaosLegacy any other questions.
