### ISSUE TITLE
Unable to get directive to work, Angular 6

### ISSUE THREAD

**Issue by mikecockrell** [AlexKhymenko/ngx-permissions#53]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
When following the examples from the setup guide, we are simply including NgxPermissionsModule.forRoot() in our imports inside our app.module.ts, we then have a nav menu component which we are trying to use the directives on to show and hide anchor links.  We are receiving the error:

"Property binding ngxPermissionsOnly not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations"

and

"Can't bind to 'ngxPermissionsOnly' since it isn't a known property of 'a'"

Is there a step we have missed in importing/including this in our project?

## Expected behavior
Desired result is that the directive works without errors

## Minimal reproduction of the problem with instructions
Follow steps above in current behavior.

## Environment

<pre><code>
Angular version: 6.0.0
ngx-permissions version: 5.0.0? (whichever is newest in npm)

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
@mikecockrell For it to work just import  NgxPermissionsModule in your modules

**Comment by AlexKhymenko** [comment]
So The main idea is this Put NgxPermissionsModule.forRoot() in you main module.
In All others modules put just NgxPermissionsModule.
In Lazy modules put  NgxPermissionsModule.forChild()
