### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by listepo-alterpost** [AlexKhymenko/ngx-permissions#55]
Hi @AlexKhymenko, when will the new version(6.0.0)?

**Comment by AlexKhymenko** [comment]
Hi @listepo-alterpost There is no version 6. The 5 is the latest version. Here you can find versions and compatibility https://github.com/AlexKhymenko/ngx-permissions/wiki/Version-dependencies

**Comment by listepo-alterpost** [comment]
@AlexKhymenko thanks
