### ISSUE TITLE
How can i use NgxPermissionsAllowStubDirective ? Can you please provide the plunker ?

### ISSUE THREAD

**Issue by Nikhilkapoor20** [AlexKhymenko/ngx-permissions#56]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x ] Documentation issue or request
</code></pre>

## Current behavior
Normally it is working fine but in the unit test i am not able to bypass the directive condition. How can i bypass it 

## Minimal reproduction of the problem with instructions
<ng-container *ngxPermissionsOnly="['SUBSCRIPTION_OWNER','USER_MANAGER']">
              <i *ngIf="!userRole?.isLastOwner" class="fa fa-user-times grid-icon" ></i>
</ng-container>

now in unit test case i have provided the 
permissionservice.Loadpermission("permissions here")

But still i am not able to get the I tag

## Environment

<pre><code>
Angular version: 5
ngx-permissions version: X.Y.Z

Browser:
- [ x] Chrome (desktop) version XX
- [ x] Chrome (Android) version XX
- [ x] Chrome (iOS) version XX
- [ x] Firefox version XX
- [ x] Safari (desktop) version XX
- [ x] Safari (iOS) version XX
- [ x] IE version XX
- [ x] Edge version XX

**Comment by AlexKhymenko** [comment]
Is this not enough? https://github.com/AlexKhymenko/ngx-permissions/wiki/Testing

**Comment by AlexKhymenko** [comment]
I will close this issue.
