### ISSUE TITLE
CanLoad functionality

### ISSUE THREAD

**Issue by volpejoaquin** [AlexKhymenko/ngx-permissions#6]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Question
Are you going to provide a service to implement the canLoad function when importing a module with lazy loading? It would be a great help!

**Comment by AlexKhymenko** [comment]
Good Day tomorrow will try to implement. But for sure on Thursday will be ready. Forgot about it :-)

**Comment by volpejoaquin** [comment]
Oh !! Thanks, buddy!

**Comment by AlexKhymenko** [comment]
Implemented documentation available here https://github.com/AlexKhymenko/ngx-permissions/wiki/Usage-with-routes#can-load-guard.
