### ISSUE TITLE
 NgxPermissionsModule forChild not expose NgxPermissionsStore

### ISSUE THREAD

**Issue by almgwary** [AlexKhymenko/ngx-permissions#60]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Expected behavior

 NgxPermissionsModule forChild not expose NgxPermissionsStore

## Environment

<pre><code>
Angular version: 5
ngx-permissions version: 4.1

**Comment by AlexKhymenko** [comment]
Hi @almgwary  This is correct behavior. Only one store should be available, and its imported by root.
