### ISSUE TITLE
TyperError in rxjs - Cant use directive and permission guard

### ISSUE THREAD

**Issue by pablochud** [AlexKhymenko/ngx-permissions#61]
When I try simply controlling access view by directive I got message error in console:
TypeError: rxjs.merge is not a function

The same problem is when I try usage with routes, but:
TypeError: rxjs.of is not a function

<pre><code>
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

Angular version: 5
ngx-permissions version: 5.0.0
rxjs version: 5.5.6

**Comment by AlexKhymenko** [comment]
Hi You should use correct version of library .
Use version 4.

With version 5 minimal rxjs dependency 6.0
With version 4 minimal rxjs dependency 5.5

**Comment by pablochud** [comment]
so I understand that it will work with the angular 4 version?

**Comment by AlexKhymenko** [comment]
Yes it will  https://github.com/AlexKhymenko/ngx-permissions/wiki/Version-dependencies

**Comment by pablochud** [comment]
Thank you for your response.
