### ISSUE TITLE
Components don't see ones loaded permissions

### ISSUE THREAD

**Issue by pablochud** [AlexKhymenko/ngx-permissions#62]
Forgive me in advance. I can't really understand why other components do not see permission I have loaded after login user.

1). I did _this.permissionsService.loadPermissions(permArray);_ in service after user is login with succeed.
2). I check if there is any permission loaded by _this.permissionsService.getPermissions()_
result: Object { add_logentry: {…}, change_logentry: {…}, delete_logentry: {…}, ... }
3). Then I change route, what is associated with the change of the component
4) In new component I check if there is still permission loaded, but I get only empty Object.
result: Object {  }

It took me a while to understand why _<div *ngxPermissionsOnly="'add_logentry'">_ doesnt work.
I would not like to load permission every time. How to solve this?

**Comment by pablochud** [comment]
I found solution: https://github.com/AlexKhymenko/ngx-permissions/issues/7

**Comment by AlexKhymenko** [comment]
Yes You are should use forRoot only in app.module
