### ISSUE TITLE
Importing NgxPermissionsConfigurationService

### ISSUE THREAD

**Issue by pablochud** [AlexKhymenko/ngx-permissions#63]
I can't finish the guide _https://github.com/AlexKhymenko/ngx-permissions/wiki/Common-use-cases#disable-element_ because there is no ngxPermissionsConfigurationService.
Anything else is working, but I would like to make custom behavior of directives.

When I try to import service it display a message "..ngx-permissions has no exported member 'NgxPermissionsConfigurationService'."

Below is a list of available imports:
![screenshot from 2018-06-22 12-35-14](https://user-images.githubusercontent.com/19813647/41772816-652e22f2-761a-11e8-8ee8-808b2a49d727.png)

<pre><code>
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

<pre><code>
Angular version: 5
ngx-permissions version: 4.0.0

**Comment by AlexKhymenko** [comment]
Use 4.1.0 version of library

**Comment by pablochud** [comment]
OK!. That's it. Thank You for reply.

**Comment by AlexKhymenko** [comment]
@pablochud No Problems Have a Great Day!!!
