### ISSUE TITLE
Error while installing ngx-permissions by this command 'npm install ngx-permissions --save'

### ISSUE THREAD

**Issue by bsangee08** [AlexKhymenko/ngx-permissions#64]
Hi,

I have downloaded this project in my local and tried to install npx-permissions.
But it is giving the following error.

PS E:\ngx-permissions-master> npm install ngx-permissions --save
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "ngx-permissions" under a package
npm ERR! also called "ngx-permissions". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2018-07-04T09_13_43_737Z-debug.log

C:\Users\admin\AppData\Roaming\npm-cache\_logs\2018-07-04T09_13_43_737Z-debug.log
![image](https://user-images.githubusercontent.com/29815610/42278351-2648e9ee-7fb8-11e8-93cf-7c42280f31b9.png)

Thanks in advance.

**Comment by AlexKhymenko** [comment]
Probably you have named project also ngx-permissions

**Comment by bsangee08** [comment]
Yeah i found that in package.json. 
Thanks.
