### ISSUE TITLE
Resolve permissions for route from a service 

### ISSUE THREAD

**Issue by mushfau** [AlexKhymenko/ngx-permissions#65]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Question or request
</code></pre>

## Current behavior

Currently we can get permissions returned from the function as a single string or an array of strings and works perfect as defined in the below example from the documentation 

```
export function testPermissions(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
  if (route.params['id'] === 42) {
    return ['MANAGER', "UTILS"]
  } else {
    return 'ADMIN'
  }
}
const appRoutes: Routes = [
  { path: 'dynamic/:id',
      component: HomeComponent,
      canActivate: [NgxPermissionsGuard],
      data: {
        permissions: {
          only: testPermissions
        }
      }
    }
];
```
## Expected behavior

I would like the permission array to be retrieved from a service. So the permission will vary based on a session object which comes with the logged in user.

how can i inject a service and call a function in that service to get the list of permission arrays??
Can i inject MyACLService as a parmerter of the testPermissions function? and do something like below?

```
export function testPermissions(route: ActivatedRouteSnapshot, state: RouterStateSnapshot, myAclService: MyACLService) {
  return myAclService.getPermissions(); // or should this be a subscribable observable ? 
}
```

A working example would be much appreciated. Or what's the better way to implement such logic ?

## Environment

<pre><code>
Angular version: 6.0.0
ngx-permissions version: 5.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Probably its better to override standart guard. Maybe this issue will help You https://github.com/AlexKhymenko/ngx-permissions/issues/30

**Comment by AlexKhymenko** [comment]
Reopen issue if you still have problem.

**Comment by McSam94** [comment]
Hi, can i have an example on how to override the standard guard? I don't really understand how #30 example works.

**Comment by AlexKhymenko** [comment]
@McSam94 The   const loaded = this.permissionsGuard.canLoad(route); will return You true or false depending on permissions you have, then You can change it to anything You want.

**Comment by McSam94** [comment]
@AlexKhymenko but where can I call web service and inject the permissions? In example #30, does it mean need to create another guard?

**Comment by AlexKhymenko** [comment]
@McSam94 Yes You create your custom guard and write logic there.
