### ISSUE TITLE
The variables inside <ng-template [ngxPermissionsOnly]="permission"> are not displayed

### ISSUE THREAD

**Issue by dsajdl01** [AlexKhymenko/ngx-permissions#68]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behaviour

When I follow the ngx-permission documentation on ng-template, any component variables referenced inside the template are not displayed. If I use text only it all works properly. 
So if permission contains ADMIN then ADMIN content is displayed. If not then Other Users content is displayed. However, once I add variables into ng-template then the variable is not displayed. 

Component variables outside of ng-template can be seen.
it also works if I used ngIf eg:  
```
<div *ngIf="readOnlyUser;then content else other_content">ignored</div>
<ng-template #content>content here... {{readOnlyMsg}}</ng-template>
<ng-template #other_content>other content here... {{AdminMsg}} </ng-template>
```

The ngxPermissions code:

```
<ng-template [ngxPermissionsOnly]="['ADMIN']"
                         [ngxPermissionsElse]="elseBlock"
                         [ngxPermissionsThen]="thenBlock">
  </ng-template>
  <ng-template #elseBlock>
            <div>Other users Content {{otherMsg}} </div>  <!-- this value of the variable is NOT visible only hard coded text Other users Content -->
  </ng-template>
 <ng-template #thenBlock>
         <div>ADMIN Content {{AdminMsg}}</div> <!-- this value of the variable is NOT visible only hard coded text ADMIN Content-->

  </ng-template>

<p> outside template Admin Msg:  {{AdminMsg}} </p> <!-- this value of the variable is visible -->
<p> outside template  other Msg:  {{otherMsg}} </p> <!-- this value of the variable is visible -->
```

## Expected behavior

The content of the variables should be visible inside ng-template

## Minimal reproduction of the problem with instructions

 

1. Use the above code ''ngxPermissions".
2. Refresh page.
3. See what happens with content inside ng-template

## Environment

<pre><code>
Angular version: 5.2.0
ngx-permissions version:  4.1.0

Browser:
- [x] Chrome (desktop) Version 67.0.3396.99
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Check out this question https://github.com/AlexKhymenko/ngx-permissions/issues/21

**Comment by AlexKhymenko** [comment]
IF You have any problems please reopen this issue.

**Comment by dsajdl01** [comment]
I wanted to use multiple component's variables and the solution [#21](https://github.com/AlexKhymenko/ngx-permissions/issues/21) did not work. Therefore I stop using this library.
