### ISSUE TITLE
Issue with get permissions

### ISSUE THREAD

**Issue by xyrintech** [AlexKhymenko/ngx-permissions#7]
I am loading the permissions in AppComponent as per the documentation and I am boot strapping the same component in app.module.ts.

When I am trying to get permissions in any other component then this returns empty object. 

I have also added the NgxPermissionsService in providers array in app.module.ts

**Comment by AlexKhymenko** [comment]
Dont do this 'I have also added the NgxPermissionsService in providers array in app.module.ts'
You should only import      NgxPermissionsModule.forRoot()

**Comment by xyrintech** [comment]
tried the same as specified above, but still this gives empty object.

**Comment by xyrintech** [comment]
I have imported NgxPermissionsModule.forRoot() in imports array in app.module.ts

**Comment by AlexKhymenko** [comment]
Can You please reproduce in plunker and give me urlhttps://plnkr.co/edit/n6Wa6hXg0JzI6e050wBt?p=preview. Recheck please you didn't add anywhere permissionsService from example in component providers. You can degug dependency injection through augury

**Comment by xyrintech** [comment]
do you use c9.io ? 
I can give you c9.io access wherein the whole code resides.

**Comment by xyrintech** [comment]
I have not added permissionsService anywhere in component provides and neither in app.module.ts.

**Comment by xyrintech** [comment]
I have one question for this too:
Lets say we have a layout.module.ts and this is the shared module with other modules.

I have added NGXPermission module as listed below:

@NgModule({
    declarations: [
        LayoutComponent,
        HeaderNavComponent,
        DefaultComponent,
        AsideNavComponent,
        FooterComponent,
        QuickSidebarComponent,
        ScrollTopComponent,
        TooltipsComponent,
        HrefPreventDefaultDirective,
        UnwrapTagDirective,
    ],
    exports: [
        LayoutComponent,
        HeaderNavComponent,
        DefaultComponent,
        AsideNavComponent,
        FooterComponent,
        QuickSidebarComponent,
        ScrollTopComponent,
        TooltipsComponent,
        HrefPreventDefaultDirective,
    ],
    imports: [
        CommonModule,
        RouterModule,
        NgxPermissionsModule.forRoot()
    ]
})

And I have added the same  NgxPermissionsModule.forRoot() in app.module.ts too as listed below:

@NgModule({
    declarations: [
        ThemeComponent,
        AppComponent
    ],
    imports: [
        LayoutModule,
        BrowserModule,
        BrowserAnimationsModule,
        AppRoutingModule,
        ThemeRoutingModule,
        AuthModule,
        RestangularModule.forRoot([AuthenticationService, Router], RestangularConfigFactory),
        ReactiveFormsModule,
        FormsModule,
        NgxPermissionsModule.forRoot()
    ],
    providers: [
        ScriptLoaderService,
        {provide: ErrorHandler, useClass: GlobalErrorHandler}
    ],
    bootstrap: [AppComponent]
})

Is this is something that can create an issue?

**Comment by xyrintech** [comment]
I think I figure it out. :)

**Comment by xyrintech** [comment]
I am calling .forRoot multiple times. 
This is where I am committing mistake.

**Comment by xyrintech** [comment]
Thanks for such a early reply, really appreciate this.

**Comment by AlexKhymenko** [comment]
You are welcome!!
