### ISSUE TITLE
Multiple permission authorization for content access

### ISSUE THREAD

**Issue by pablochud** [AlexKhymenko/ngx-permissions#70]
For simple example, when I set two permission I expect the button will show up if user has two permission. not only one of them. At its simplest, This solution provide logic OR, I expect logic AND.
Do you have solution for that in library? Wrapping permission multiple times in `<div>` is not good.

`                <button *ngxPermissionsOnly="['pr_active_details','pr_closed_issue']" type="button" class="btn btn-secondary icon-size-small" value="detail">
                    <em class="fa fa-info"></em>
 </button>`

**Comment by AlexKhymenko** [comment]
@pablochud  You should use roles is this case  https://github.com/AlexKhymenko/ngx-permissions/wiki/Managing-roles


NgxRolesService
  .addRole('ROLE_NAME', ['pr_active_details', 'pr_closed_issue', 'permissionNameC', ...])

And then <button *ngxPermissionsOnly="['ROLE_NAME']" type="button" class="btn btn-secondary icon-size-small" value="detail"> <em class="fa fa-info"></em> </button>
