### ISSUE TITLE
Having issues with unit tests

### ISSUE THREAD

**Issue by shamoons** [AlexKhymenko/ngx-permissions#71]
Trying to write tests, but I get:

```
Can't bind to 'ngxPermissionsOnly' since it isn't a known property of 'div'. ("
    </div>
            </div>
                <div [ERROR ->]*ngxPermissionsOnly="['ADMIN', 'GUEST']" class="m-portlet__head-tools">
                    <ul class="nav nav-pil"): ng:///DashboardModule/DashboardComponent.html@35:10
Property binding ngxPermissionsOnly not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
                    </div>
                </div>
                [ERROR ->]<div *ngxPermissionsOnly="['ADMIN', 'GUEST']" class="m-portlet__head-tools">
                    <ul class="nav na"): ng:///DashboardModule/DashboardComponent.html@35:5
```

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z
ngx-permissions version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
@shamoons Hi thats why i have created this one https://github.com/AlexKhymenko/ngx-permissions/wiki/Testing

**Comment by AlexKhymenko** [comment]
@shamoons I will close this issue if you have problems please let me know

**Comment by msonnad** [comment]
![image](https://user-images.githubusercontent.com/34677240/48882321-aa298c00-ee3f-11e8-8fbf-e8e22aa43e2a.png)

**Comment by AlexKhymenko** [comment]
@msonnad Hi You need to import in the module where You use it.

**Comment by msonnad** [comment]
Hi, Is their any dependency on rxjs versions . I am using rxjs5.5.2 version. What is the angular version supported.?
Our version of angular is 5.0

**Comment by AlexKhymenko** [comment]
@msonnad Please look on this pagehttps://github.com/AlexKhymenko/ngx-permissions/wiki/Version-dependencies
Will be your version 4.1.0

**Comment by msonnad** [comment]
Thanks, i am able to find the correct version now.
