### ISSUE TITLE
Usage question - ngxPermission directive

### ISSUE THREAD

**Issue by architechcro** [AlexKhymenko/ngx-permissions#72]
## I'm submitting a

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x ] Documentation issue or request
</code></pre>

## Current behavior
ngxPermissionOnly directive syntax is not working as described in documentation. I've tested several syntax cases and only one that works throws typescript error
tested: 

```
     1. <div *ngxPermissionsOnly="['GUEST']">GUEST</div>
     2. <div *ngxPermissionsOnly="GUEST">GUEST - 2</div>
     3. <div *ngxPermissionsOnly="'GUEST'">GUEST - 3</div>
     4. <div *ngxPermissionsOnly="['GUEST']">GUEST - 4</div>
     5. <div *ngxPermissionsOnly="['ADMIN']">ADMIN</div>
     6. <div *ngxPermissionsOnly="['USER']">USER</div>
     7. <div *ngxPermissionsOnly="'GUEST', 'ADMIN'">GUEST, ADMIN - 3</div>
```

Only GUEST-2 ( example 2. ) is displayed, but there is a build error: 
[Angular] Identifier 'GUEST' is not defined. The component declaration, template variable declarations, and element references do not contain such a member

I've tried several more syntax combinations and only permissions without '' work. e.g. 
*ngxPermissionsOnly="GUEST"
*ngxPermissionsOnly="[ADMIN, GUEST]"

## Expected behavior

Examples 1., 3., 4., 5., 6., 7. should work ( depending on the active roles )

## Minimal reproduction of the problem with instructions

Installation done as described.
Roles assigned 

`rolesService.addRole(element.roleName, element.permissions);`

Roles service returns assigned roles as expected
```
    this.rolesService.roles$.subscribe( res => {
      this.roles = res;
    });
```

## Environment

<pre><code>
Angular version: 6.0.1
ngx-permissions version: 5.0.0

Browser:
- [x ] Chrome (desktop) version 67.0.3396.99 (Official Build) (64-bit)
- [ x] Chrome (Android) version 68.0.3440.85
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by ranjithsiam** [comment]
I'm also having the same issue. My angular version is 6.0.0 and ngx-permission version is 5.0.0. Checked with all the syntax and its not working. Kindly help with this issue.

**Comment by AlexKhymenko** [comment]
@architechcro Its actully working :-) When You are using roles you should also have permissions working. Maybe use only permissions without roles for now. When you write like this *ngxPermissionsOnly="GUEST" You are referencing variable in the component thats why you have error. Cause in aot mode its checking variables

**Comment by ranjithsiam** [comment]
@AlexKhymenko I'm using the permissions only. I have loaded the permissions using this.permissionService.loadPermissions(["A"]) and in the routing side added the below line,
path: 'product', 
                {
                 path:'product'
                 loadChildren: './product/product.module#ProductModule', 
                canActivate : [NgxPermissionsGuard],
                data: {
                    permissions: {
                      only: ['A'],
                      except: ['SA'],
                      redirectTo: '/user'
                    }
                   }
Please correct me if I'm wrong.

**Comment by kalpanavr** [comment]
Hi @AlexKhymenko I too having the same issue. 
I'm having the application with version Angular 6.0 and ngx-permissions 5.0. I'm using permissions only in my application. 
Explanation : During the user's login, I'm loading the permissions using the below code,
`this.permissionService.loadPermissions(["Admin"])`
and in the routing part I have used as below,
`
{ 
path:'product' loadChildren: './product/product.module#ProductModule',
canActivate : [NgxPermissionsGuard], 
data: { 
permissions: { only: ['SuperAdmin'], 
except: ['Admin'], 
redirectTo: '/user' 
} 
}`

Expected : Only the SuperAdmin can access the product routing. 
Issue : Allowing all users to access the product route.

Kindly help me with this.

**Comment by AlexKhymenko** [comment]
@kalpanavr probably you should use canLoad not canActivate and make sure that the permissions are available before application starts

**Comment by kalpanavr** [comment]
@AlexKhymenko Thanks for your reply. I tried with canLoad but I couldn't achieve the expected result. Can you tell me how to check whether the permissions are loaded or not. Because I tried with the below code but its saying as no such method.

`var permissions = NgxPermissionsService.getPermissions();
`

**Comment by kalpanavr** [comment]
But i'm getting only an object as below screenshot
![per](https://user-images.githubusercontent.com/42338695/44078373-efea7c92-9fc3-11e8-9e1e-4b77d0211ad5.PNG)
 when using this,
`You should import ngxPermissionsService in
constructor(private ngxPermissionsService: NgxPermissionsService)

And then do this.ngxPermissionsService.getPermissions();`
