### ISSUE TITLE
missing info on v6

### ISSUE THREAD

**Issue by davidkarlsen** [AlexKhymenko/ngx-permissions#75]
Can you provide release-info / migration-info for version 6 of the library?
https://www.npmjs.com/package/ngx-permissions

**Comment by AlexKhymenko** [comment]
The only breaking change its moving to angular cli library generator. It can break some builds so I published version 6

**Comment by davidkarlsen** [comment]
Hm - upgrading broke for me on latest angular 6.1.x

**Comment by AlexKhymenko** [comment]
What exactly did it broke ?

**Comment by AlexKhymenko** [comment]
@davidkarslen it would be very helpful :-) cause other people can have the same problem

**Comment by AlexKhymenko** [comment]
@davidkarlsen tested on several app everything works....

**Comment by AlexKhymenko** [comment]
@davidkarlsen If You have this error fixed in Function calls are not supported in decorators but 'NgxPermissionsModule' was called. version 6.0.1

**Comment by davidkarlsen** [comment]
Indeed it is:
```
14:09:45 [buildAndPackage] ERROR in Error during template compile of 'AppModule'
14:09:45 [buildAndPackage]   Function calls are not supported in decorators but 'NgxPermissionsModule' was called.
```

**Comment by davidkarlsen** [comment]
Verified working with 6.0.1 - thanks a lot!

**Comment by sam17896** [comment]
This should be in document.. for angular 6 -> ngx-permission 6.0.X should be used
