### ISSUE TITLE
Async object inside ngxPermissionsOnly doesn't work

### ISSUE THREAD

**Issue by fravezzimattia** [AlexKhymenko/ngx-permissions#78]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ x ] Documentation issue or request
</code></pre>

## Current behavior

###Component
<pre><code>
export class MyComponent implements OnChanges {
    @Input("id")
    id: number;
    obj: Object;

ngOnChanges(changes: SimpleChanges) {
        this.apiService.getById(changes.id.currentValue)
            .takeWhile(() => this.isAlive)
            .subscribe(res => {
                this.obj= res;
            });
    }
}
</code></pre>
###Template
```
<div *ngFor="let item of obj?.list">
            <!-- 1   IT WORKS!!! -->
            <div *ngxPermissionsOnly="['ADMIN']">
                Hello World!
            </div>
            <!-- 2   IT WORKS!!!-->
            <button>
                {{item.name}}
            </button>
            <!-- 3 DOES NOT WORK!!! -->
            <div *ngxPermissionsOnly="['ADMIN']">
                <button>
                    {{item.name}}
                </button>
            </div>
</div>
```
First and Second example works correctly but in third the button appear empty without any text!  Why?

## Environment

<pre><code>
Angular version: 4.4.3
ngx-permissions version: 3.2.4

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
@fravezzimattia Do you have this problem in the newest version?

**Comment by kmturley** [comment]
I have the same issue!
`<p>{{ community | async | json }}</p>`

Renders fine outside ngxPermissions, but is null when inside *ngxPermissionsOnly="['reader']"

**Comment by fravezzimattia** [comment]
> @fravezzimattia Do you have this problem in the newest version?

I moved permission into controller 🥇

**Comment by mariusl-a** [comment]
Did you try wrap ng-container around it?

```
<ng-container *ngIf="community | async; let data">
	<div *ngxPermissionsOnly="['reader']">
		<p>{{ data | json }}</p>
	</div>
</ng-container>
```

**Comment by kmturley** [comment]
Yes that works! but not the ideal solution :)

**Comment by kmturley** [comment]
I tried to replicate in Plunker using an HTTP request, but it seems to work there:
https://plnkr.co/edit/4evjZE?p=preview

**Comment by AlexKhymenko** [comment]
@fravezzimattia @kmturley Can you please try with version 6.0.3

**Comment by AlexKhymenko** [comment]
@fravezzimattia @kmturley Can you please try with version 6.0.4

**Comment by kmturley** [comment]
seems to work for me! woohoo!

**Comment by AlexKhymenko** [comment]
@fravezzimattia If You still have this issue please reopen it
