### ISSUE TITLE
ngxPermissionOnly not working ngFor

### ISSUE THREAD

**Issue by thapld** [AlexKhymenko/ngx-permissions#81]
I cannot display menu aside when use ngFor 
<ng-container *ngFor="let child of menuAsideService.menuList2$">
		<ng-container *ngxPermissionsOnly="child.permissions">
			<a
				[routerLink]="[child.url]"
				routerLinkActive="active"
				 class="menu-item">
				<span translate>{{child.title}}</span>
			</a>
		</ng-container>
	</ng-container>
If I remove ngFor then it works.
"<li class="m-menu__item"  *ngxPermissionsOnly="['eim:group:view']">daad</li>"

**Comment by AlexKhymenko** [comment]
@thapld probably you need to use async pipe in ngFor
`<ng-container *ngFor="let child of menuAsideService.menuList2$ | async">
`

**Comment by AlexKhymenko** [comment]
@thapld here is plunker https://plnkr.co/edit/vCpRKTCbqtOECDyb6r8T?p=preview

Go to permissions page > add Admin permissions

File is src/permissions.component.ts

**Comment by thapld** [comment]
Thank you so much. I will try it.
