### ISSUE TITLE
ngx-permissions are not working for lazy loading

### ISSUE THREAD

**Issue by bsangee08** [AlexKhymenko/ngx-permissions#85]
Hi,

When adding ngx-permissions to my project, compilation error happens. My code contains multiple lazy-loaded modules and each one makes use of *ngxPermissionsOnly

Tried importing NgxPermissionsModule, NgxPermissionsModule.forRoot(), NgxPermissionsModule.forChild() in both main app module and child layout module, but nothing worked.

Please refer to the stackoverflow link below for routing and module info in root and child modules:;
 https://stackoverflow.com/questions/52815417/ngxpermissions-not-working-with-lazy-loaded-module

Please help me to resolve this issue.

**Comment by mariusl-a** [comment]
This works for me:
import NgxPermissionsModule.forRoot() in app.module.ts
import NgxPermissionsModule.forChild() in all child modules

**Comment by bsangee08** [comment]
Thanks for your reply.

Could you please tell where am I going wrong?
https://stackoverflow.com/questions/52815417/ngxpermissions-not-working-with-lazy-loaded-module

**Comment by ShubhamJainSJ** [comment]
Update ngx-permissions package to latest version 6.0.2 and it should work fine.

**Comment by mariusl-a** [comment]
Can close this one - Was due to wrong version.
