### ISSUE TITLE
[Feature Request] Add pipes for handling permissions

### ISSUE THREAD

**Issue by adammedford** [AlexKhymenko/ngx-permissions#88]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Your current implementation relies on structural directives which cannot share elements. *ngIf must be placed on a separate line from *ngxPermissions.

This could be avoided by providing an ngxPermissionsPipe that accepts an array of Roles/Permissions as its value and a strategy 'except' | 'only' (etc) and returns true or false based on that permissions check

```
<div *ngxPermissionsOnly="['ADMIN', 'GUEST']">
  <div *ngIf="true">
    You can see this text congrats
  </div>
 </div>
```

becomes

```
  <div *ngIf="['ADMIN', 'GUEST'] | ngxPermissions:'only' && true">
    You can see this text congrats
  </div>
```

**Comment by AlexKhymenko** [comment]
Unfortunately it requires a lot of time that i don't have.

**Comment by AlexKhymenko** [comment]
Actually its impossible cause i need to have template :-)

**Comment by entspannt** [comment]
I also needed a pipe to handle permissions. Here's my solution:

`
import { Pipe, PipeTransform } from '@angular/core';
import { NgxPermissionsService } from 'ngx-permissions';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { Store } from '@ngrx/store';
import { userAccessRights } from '../auth/auth.selectors';

@Pipe({
    name: 'permission',
})
export class PermissionPipe implements PipeTransform {
    constructor(
        private permissionService: NgxPermissionsService,
        private store: Store<any>
    ) {}
    transform(value: string): Observable<boolean> {
        return this.store
            .select(userAccessRights)
            .pipe(map(() => !!this.permissionService.getPermission(value)));
    }
}
`

I use the store selector to tell the pipe, that the permissions changed.

The pipe can then be used like this:
`{{'transports|READ' | permission | async}}`
