### ISSUE TITLE
Using ngx-permissions in Angular Library Component

### ISSUE THREAD

**Issue by matthew-valenti** [AlexKhymenko/ngx-permissions#90]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior
I'm am using an Angular 7 library that has shared components (for use with other Angular apps). I'm trying to add permissions functionality to a my shared component in the library. Permission directives work okay in the component but the injected NgxPermissionsService has no data i.e. this.ngxPermissionsService.getPermissions() returns empty. I've tried everything I can think of so any hints/tips much appreciated.

Angular Library documentation:
https://github.com/angular/angular-cli/wiki/stories-create-library. 

## Expected behavior
this.ngxPermissionsService.getPermissions() returns permissions.

## Minimal reproduction of the problem with instructions
1. Create Angular library.
2. Create component in library.
3. Add NgxPermissionsModule to shared-component.module.ts (in library).
4. Add library component to new app component (in Angular app)
5. Import shared-component.module.ts in app component.
5. App component is lazy loaded so add NgxPermissionsModule to both app.module.ts and app component module.ts.

## Environment
<pre><code>
Angular version: 7.0.6
ngx-permissions version: 6.0.4

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Hi @matthew-valenti If You still have problems can You give me feedback.

**Comment by alyeldegwy** [comment]
I got the same problem here I'm trying to load NgxPermissionsModule in a sharedModule but I'm getting a StaticInjectorError(AppModule)[NgxPermissionsService]
