### ISSUE TITLE
How to react to unauthorized situation on route to inform user?

### ISSUE THREAD

**Issue by MikeDabrowski** [AlexKhymenko/ngx-permissions#91]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

When using this library with routes, how can I react to unauthorized access just before redirection to show simple popup informing user that it has no access to that route?

## Minimal reproduction of the problem with instructions

Create simple project with at least 2 routes. Protect one route with guard and make it redirect to the other one.

## Environment

<pre><code>
Angular version: 7.0.3
ngx-permissions version: 6.0.4

Browser:
- [x] Chrome (desktop) version 71
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
@MikeDabrowski Sorry for late response but You can overwrite guard. Here is example https://github.com/AlexKhymenko/ngx-permissions/issues/30

**Comment by MikeDabrowski** [comment]
@AlexKhymenko 
Thanks, in the end that was what I used just couple days ago.
