### ISSUE TITLE
Custom strategies not shared between modules / components

### ISSUE THREAD

**Issue by MikeDabrowski** [AlexKhymenko/ngx-permissions#92]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

I use lazyloaded modules so I am importing forRoot() in app.module and forChild() in child modules.
I created custom strategy to handle disabling buttons (like in the docs) and I set  this config in APP_INITIALIZER or app.module. 
The problem is that it only affects this forRoot part - only in app module buttons get disabled. Lazyloaded modules have different instance of that config service responsible for strategies. 
I found out that I can add strategy in one of lazyloaded modules and its available in others.

## Expected behavior
There should be a way to define custom strategies per whole app and it should be better documented.

## Environment

<pre><code>
Angular version: 7.1.4
ngx-permissions version: ^6.0.4

Browser:
- [x] Chrome (desktop) version 71
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
@MikeDabrowski Can You please post code or even better reproduction so I can help ?

**Comment by MikeDabrowski** [comment]
https://stackblitz.com/edit/angular-ngx-permission-issue-92

Managed to find some time to do this. 
While doing it I found out that each `.forChild()` creates its own 'instance' of config. In my case it was shared because I used CoreModule which provided one common 'instance' further. 

Hope you will understand from the code, but if something is not clear - let me know. Your lib solves my many problems while creating new (but less) ones 😁

**Comment by AlexKhymenko** [comment]
@MikeDabrowski  Thank You Very much :-) I will try to reduce problems that im creating :-)

**Comment by AlexKhymenko** [comment]
@MikeDabrowski Fixed in 6.0.5 version :-) Thank You very much for creating bug request and reproduction of the problem.

**Comment by NishanthRE** [comment]
Hi @AlexKhymenko,
 I am using canActivateChild in the child module, its working fine without any lack. But when i left the application for 10-15 mins and try to refresh the application i am redirecting to the permission denied component instead of authorized component even all the permissions get loaded. please see the integration below.

![Screenshot (148)](https://user-images.githubusercontent.com/43135722/65678655-8c512880-e008-11e9-8248-54fc0af5d561.png)
