### ISSUE TITLE
ERROR in : Can't bind to 'ngxPermissionsOnly' since it isn't a known property of 'p'.  

### ISSUE THREAD

**Issue by constantinosergiou** [AlexKhymenko/ngx-permissions#93]
## I'm submitting a...
ERROR in : Can't bind to 'ngxPermissionsOnly' since it isn't a known property of 'p'.  
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: 7.0.0
ngx-permissions version:^6.0.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by yuniel-acosta** [comment]
I have the same problem, someone has a solution
