### ISSUE TITLE
Permission only running 1 component

### ISSUE THREAD

**Issue by desenvolvedorfmais** [AlexKhymenko/ngx-permissions#94]
Permission only running 1 component

I'm using the template
https://www.creative-tim.com/product/material-dashboard-angular2#
I applied the admin permission on the component sidebar.component and dashboard.component. And include the code in the sidebar.component.ts,

`this.permissionsService.loadPermissions (perm) ;`

. However on dashboard.component it is leaving the card invisible, and is not considering loadPermissions to include in the sidebar. How do I get ngx Permissions to share also for components that have the same ngxPermissionsOnly directive.

Or will I have to again apply in the dashboard.component class the same validation I did on the other component?

![dashboard](https://user-images.githubusercontent.com/35231033/53180475-6546fa00-35d4-11e9-9357-58c2357cf716.png)

![sidebarclass](https://user-images.githubusercontent.com/35231033/53180485-69731780-35d4-11e9-98e2-d7df8e3ec2b1.png)

![sidebarcomponent](https://user-images.githubusercontent.com/35231033/53180497-6e37cb80-35d4-11e9-9312-b8e86054dbca.png)

![app](https://user-images.githubusercontent.com/35231033/53180504-7132bc00-35d4-11e9-97d4-5105490f10dc.png)

**Comment by AlexKhymenko** [comment]
@desenvolvedorfmais Please show me the module configuration :-) maybe You used 2 forRoot methods.

**Comment by desenvolvedorfmais** [comment]
Thanks, get missed to include in the main module that load other services. Thanks for answering.
