### ISSUE TITLE
HasOnlyRoles Does Not Appear To Be Working

### ISSUE THREAD

**Issue by frostdevelopment979** [AlexKhymenko/ngx-permissions#95]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
While running a test case, I am adding two roles. When using the hasOnlyRoles('role1'), it returns true despite their being role1 and role2 added. 

## Expected behavior
Should return false if the role service contains more than the role(s) passed into hasOnlyRoles.

## Minimal reproduction of the problem with instructions
One can create a new project. I am doing the following:

constructor(private roleService: NgxRolesService) {}
......
 this.roleService.addRole('role1', () => {
      return true;
    });

    this.roleService.addRole('role2', () => {
      //return this.ROLE_LIST.includes(userInfo.role);
      return false;
    });
....
Then as I test: 
roleService.hasOnlyRoles('role1').then(values => {
      console.log(values);
      expect(values).toEqual(true);
    });

The test case passes!

## Environment

<pre><code>
Angular CLI: 6.1.5
Node: 10.15.2
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.4.6
@angular-devkit/schematics        0.7.5
@angular/cdk                      5.2.0
@angular/cli                      6.1.5
@angular/material                 6.4.7
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.16.3

ngx-permissions version: 6.0.5

Browser:
- [x ] Chrome (desktop) version 73.0.3683 (Windows 7.0.0)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by frostdevelopment979** [comment]
Real quick, wanted to thank you for this library. It is really slick and useful.

**Comment by AlexKhymenko** [comment]
Hi @frostdevelopment979 You wrote 
`this.roleService.addRole('role1', () => {
  return true;
});` and then of cource 

`roleService.hasOnlyRoles('role1').then(values => {
console.log(values);
expect(values).toEqual(true);
});` will pass.

`roleService.hasOnlyRoles('role2').then(values => {
console.log(values);
expect(values).toEqual(true);
});` should not pass :-)

**Comment by frostdevelopment979** [comment]
this.roleService.addRole('role1', () => { return true; }); 
this.roleService.addRole('role2', () => { return true; }); 
roleService.hasOnlyRoles('role1').then(values => { console.log(values); expect(values).toEqual(true); }); should fail right?

**Comment by AlexKhymenko** [comment]
@frostdevelopment979 it should pass :-) Cause you are returning true.

**Comment by frostdevelopment979** [comment]
It seems as though the validation function is playing some odd role in this, which I personally wouldn't expect. Just my humble opinion. It seems like the roles service should be returning true or false solely in relation to if it has that specified role. Perhaps I just miss understand how this should be used. Don't get me wrong, the library is still getting me what I need rather efficiently but it does have some nuance to it that I do not fully understand. I will close this issue having said this. Thank you for your help.
