### ISSUE TITLE
Description of add permissions in Defining roles

### ISSUE THREAD

**Issue by Niconal** [AlexKhymenko/ngx-permissions#96]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior

Managing roles
Defining roles
Individual roles
//permissionNameA,B,C should be defined by permissions service
//this.ngxPermissionsService.loadPermissions(["permissionNameA", "permissionNameB", "permissionNameC"])
// If at least one is not available the check will fail.
## Expected behavior

I thought it should be this.ngxPermissionsService.addPermission...., not this.ngxPermissionsService.loadPermissions.

## Environment

<pre><code>
Angular version: X.Y.Z
ngx-permissions version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
@Niconal  Hi the difference loadPermissions will remove all old permissions. and add permission will add permission to existing one. I will look into documentation and upgrade it so there will be no confusion

**Comment by AlexKhymenko** [comment]
Updated desription
