### ISSUE TITLE
Request For RemoveAllRolesBut...

### ISSUE THREAD

**Issue by frostdevelopment979** [AlexKhymenko/ngx-permissions#97]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Not able to easily iterate through current roles and remove only those that do not match a new role (string). 

## Expected behavior
Would like a mix between roleservice.flush() and rolservice.removeRole(nameOfRole), called:
removeAllBut([]).

Why not just flush and add? 

Because when you remove all at once, those html elements with *ngxPermissionsOnly="<map_of_roles>, will vanish (because there are no roles that match the map) and not bother to render again after adding in the new role. 

## Minimal reproduction of the problem with instructions
Example div:

`<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <ng-template ngFor let-tab [ngForOf]="tabs">
                  <a  routerLink="{{tab.route}}" routerLinkActive="active" *ngxPermissionsOnly="tab.role" class="nav-link">
                      {{tab.title}}
                  </a>
                </ng-template>
          </div>`

Then flush all roles, then add back (without refreshing the page).

## Environment
Angular CLI: 6.1.5
Node: 10.15.2
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.4.6
@angular-devkit/schematics        0.7.5
@angular/cdk                      5.2.0
@angular/cli                      6.1.5
@angular/material                 6.4.7
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.16.3

ngx-permissions version: 6.0.5

Browser:
- [x ] Chrome (desktop) version 73.0.3683 (Windows 7.0.0)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by AlexKhymenko** [comment]
Hi @frostdevelopment979 i will look into the issue when its not rerenders. But im quite busy now. On weekends probably
