### ISSUE TITLE
Bundle size - RXJS

### ISSUE THREAD

**Issue by hugoj-goncalves** [AlexKhymenko/ngx-permissions#98]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Whole Rxjs gets into the final bundle.

## Expected behavior
Only used functions should be included.

## Minimal reproduction of the problem with instructions

Using the getting started from angular as a base.
- ng new my-app
Simply running *npm install ngx-permissions* and importing the module into the *app.module.ts* like this.

```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

import { NgxPermissionsModule } from 'ngx-permissions';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    NgxPermissionsModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```
## Environment

Angular version: ~7.2.0
ngx-permissions version: ^6.0.5

Bundle analyzer without ngx-permissions: 

![image](https://user-images.githubusercontent.com/10927715/56268182-1f377f80-60c7-11e9-91be-a1f5a3b4a5f2.png)

With ngx-permissions:

![image](https://user-images.githubusercontent.com/10927715/56268233-31192280-60c7-11e9-9015-475c93ac4c4c.png)

**Comment by AlexKhymenko** [comment]
@hugoj-goncalves strange i thought i imported everything correctly. Will investigate but can do this only on weekends.

**Comment by hugoj-goncalves** [comment]
I couldn't find anything wrong, but simply removing the umd.js file seems to solve the issue.
I guess it's trying to use the umd.js file even when it shouldn't.

**Comment by AlexKhymenko** [comment]
@hugoj-goncalves what version of cli are you using?

**Comment by hugoj-goncalves** [comment]
strange...

![image](https://user-images.githubusercontent.com/10927715/56579748-54e8d680-65a7-11e9-91d3-8d9ab0e1ff51.png)

**Comment by AlexKhymenko** [comment]
@hugoj-goncalves Thank You will check on this version.

**Comment by AlexKhymenko** [comment]
@hugoj-goncalves i have rechecked everything and moved to cli. there should be no problems this time. If You have more problems please reopen issue
